// GENERATED BY @supacloud/compiler — do not edit

import { WebhookInputSchema, WebhookKeySchema, WebhookLookupSchema, WebhookReceiptSchema } from "../webhook/contracts";
import { UpdateWebhook } from "../webhook/update.command";
import { WebhookController } from "../webhook/webhook.controller";

export interface CompiledRoute {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";
  path: string;
  handler: string;
  body?: unknown;
  params?: unknown;
  query?: unknown;
  response?: unknown;
  command?: string;
  guards?: string[];
  canMatch?: string[];
  canDeactivate?: string[];
  resolvers?: Record<string, string>;
  redirectTo?: string;
  pathMatch?: "full" | "prefix";
  paramTransforms?: Record<string, "number" | "boolean" | "string">;
  paramDefaults?: Record<string, unknown>;
  queryTransforms?: Record<string, "number" | "boolean" | "string">;
  queryDefaults?: Record<string, unknown>;
  title?: string;
  data?: Record<string, unknown>;
  aspects?: CompiledAspect[];
  invoker?: (
    controller: unknown,
    request: {
      params?: Record<string, unknown>;
      query?: Record<string, unknown>;
      body?: unknown;
      headers?: Record<string, unknown>;
      context?: unknown;
    },
  ) => Promise<unknown> | unknown;
}

export interface CompiledCommand {
  rpc?: string;
  className: string;
  name: string;
  permission: string;
  transaction: "required" | "none";
  audit?: string;
  idempotency: "required" | "none";
  standalone?: boolean;
  aspects?: CompiledAspect[];
}

export interface CompiledJob {
  className: string;
  name: string;
  serviceKey: string;
  scope: "application" | "request" | "job";
  aspects?: CompiledAspect[];
}

export interface CompiledAspectContext {
  kind: "route" | "command" | "job";
  name: string;
  input: unknown;
  request?: Request;
  requestContext?: unknown;
  scope?: Record<string, unknown>;
  services?: Record<string, unknown>;
  metadata?: unknown;
}

export type CompiledAspect = (
  context: CompiledAspectContext,
  next: () => unknown | Promise<unknown>,
) => unknown | Promise<unknown>;

export interface CompiledController {
  path: string;
  serviceKey: string;
  scope: "application" | "request" | "job";
  routes: CompiledRoute[];
}

export interface CompiledModule {
  name: string;
  createServices(
    deps: Record<string, unknown>,
    imported: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  createRequestScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Promise<Record<string, unknown>>;
  destroyRequestScope?(scope: Record<string, unknown>): Promise<void>;
  createJobScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Promise<Record<string, unknown>>;
  destroyJobScope?(scope: Record<string, unknown>): Promise<void>;
  controllers: CompiledController[];
  commands: CompiledCommand[];
  jobs: CompiledJob[];
  aspects?: CompiledAspect[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isFunction(value: unknown): value is (...args: unknown[]) => unknown {
  return typeof value === "function";
}

function resolveFactoryValue(value: unknown): unknown {
  if (!isRecord(value) || !isFunction(value.factory)) return undefined;
  return value.factory();
}

const scopeDestructions = new WeakMap<object, Promise<void>>();

function destroyScopeInstances(
  scope: Record<string, unknown>,
  plan: readonly { key: string; index?: number }[],
): Promise<void> {
  const pending = scopeDestructions.get(scope);
  if (pending) return pending;
  const destruction = Promise.resolve().then(async () => {
    const errors: unknown[] = [];
    const seen = new Set<unknown>();
    for (const entry of [...plan].reverse()) {
      const value = scope[entry.key];
      const instance = entry.index === undefined ? value
        : Array.isArray(value) ? value[entry.index] : undefined;
      if (seen.has(instance)) continue;
      seen.add(instance);
      try {
        if (isRecord(instance) && isFunction(instance.onDestroy)) {
          await instance.onDestroy();
        } else if (isRecord(instance) && isFunction(instance.ngOnDestroy)) {
          await instance.ngOnDestroy();
        }
      } catch (error) {
        errors.push(error);
      }
    }
    if (errors.length > 0) throw new AggregateError(errors, "Scope destruction failed");
  });
  scopeDestructions.set(scope, destruction);
  return destruction;
}

export function createCompiledModules(): CompiledModule[] {
  return [
    {
      name: "webhook",
      createServices: createWebhookServices,
      createRequestScope: createWebhookRequestScope,
      destroyRequestScope: destroyWebhookRequestScope,
      controllers: [
      {
        path: "/webhooks",
        serviceKey: "webhookController",
        scope: "request",
        routes: [{ method: "POST", path: "/update", handler: "update", body: WebhookInputSchema, response: WebhookReceiptSchema, invoker: async (ctrl: unknown, req: { params?: Record<string, unknown>; query?: Record<string, unknown>; body?: unknown; headers?: Record<string, unknown>; context?: unknown }) => { if (!isRecord(ctrl)) throw new TypeError("Route controller is not an object"); const handler = ctrl["update"]; if (typeof handler !== "function") throw new TypeError("Route handler update is not callable"); return await Reflect.apply(handler, ctrl, [req.body, req.headers?.["idempotency-key"]]); } }, { method: "GET", path: "/receipts/:key", handler: "receipt", params: WebhookKeySchema, response: WebhookLookupSchema, invoker: async (ctrl: unknown, req: { params?: Record<string, unknown>; query?: Record<string, unknown>; body?: unknown; headers?: Record<string, unknown>; context?: unknown }) => { if (!isRecord(ctrl)) throw new TypeError("Route controller is not an object"); const handler = ctrl["receipt"]; if (typeof handler !== "function") throw new TypeError("Route handler receipt is not callable"); return await Reflect.apply(handler, ctrl, [(req.params?.["key"] !== undefined ? req.params?.["key"] : undefined)]); } }],
      }
    ],
      commands: [{ className: "UpdateWebhook", name: "webhook.update.v1", permission: "webhook.update", transaction: "required", audit: "webhook.updated", idempotency: "required", rpc: "webhookUpdate" }],
      jobs: [],
    },
  ];
}

export async function initializeApplication(services: Record<string, unknown>): Promise<void> {
  const initializers = [services.environmentInitializer ?? services["supacloud.environment-initializer"], services.appInitializer ?? services["supacloud.app-initializer"]];
  for (const group of initializers) {
    if (Array.isArray(group)) {
      for (const init of group) {
        if (isFunction(init)) await init();
      }
    } else if (isFunction(group)) {
      await group();
    }
  }
}

export async function destroyApplication(services: Record<string, unknown>): Promise<void> {
  const destroyRef = services.destroyRef ?? services["supacloud.destroy-ref"];
  if (isRecord(destroyRef) && isFunction(destroyRef.destroy)) {
    await destroyRef.destroy();
  } else if (isRecord(destroyRef) && Array.isArray(destroyRef._teardowns)) {
    for (const teardown of [...destroyRef._teardowns].reverse()) {
      if (isFunction(teardown)) await teardown();
    }
  }
  const instances = Object.values(services);
  for (const inst of instances.reverse()) {
    if (isRecord(inst) && isFunction(inst.onDestroy)) {
      await inst.onDestroy();
    } else if (isRecord(inst) && isFunction(inst.ngOnDestroy)) {
      await inst.ngOnDestroy();
    }
  }
}

function createWebhookServices(
  deps: Record<string, unknown>,
  imported: Record<string, Record<string, unknown>>,
): Record<string, unknown> {
  const updateWebhook = new UpdateWebhook(deps.webhookEnvironment as ConstructorParameters<typeof UpdateWebhook>[0]);
  return { updateWebhook };
}
async function createWebhookRequestScope(
  services: Record<string, unknown>,
  ctx: unknown,
  imported: Record<string, Record<string, unknown>> = {},
): Promise<Record<string, unknown>> {
  const scope: Record<string, unknown> = {};
  try {
    const webhookController = new WebhookController(services.updateWebhook as ConstructorParameters<typeof WebhookController>[0], ctx as ConstructorParameters<typeof WebhookController>[1]);
    scope["webhookController"] = webhookController;
    return scope;
  } catch (error) {
    try {
      await destroyWebhookRequestScope(scope);
    } catch (cleanupError) {
      console.error("supacloud: request scope rollback failed for webhook", cleanupError);
    }
    throw error;
  }
}
async function destroyWebhookRequestScope(scope: Record<string, unknown>): Promise<void> {
  await destroyScopeInstances(scope, []);
}
