import { readable } from "svelte/store";
export const page = $state<{ params: { ref: string | undefined } }>({ params: { ref: "a" } });
export const notifications: Array<{ kind: string; message: string }> = [];
export const toast = {
  success(message: string) { notifications.push({ kind: "success", message }); },
  error(message: string) { notifications.push({ kind: "error", message }); },
  warning(message: string) { notifications.push({ kind: "warning", message }); },
};
const translations: Record<string, string> = {
  "OAuthServer.title": "OAuth Server",
  "OAuthServer.subtitle": "OAuth 配置与客户端",
  "OAuthServer.unavailable": "OAuth 配置暂时不可用。",
  "OAuthServer.partial_apply_warning": "配置已保存，但依赖项目刷新失败或状态未知。尚未完成全部应用。",
  "OAuthServer.configuration_saved": "OAuth 配置已保存。运行状态尚未验证。",
  "OAuthServer.migration_uncertain": "迁移结果未确认，配置可能已保存。请刷新核对，不要直接重复提交。",
  "OAuthServer.mutation_uncertain": "操作结果未确认，服务端可能已执行。请先刷新核对，不要直接重复提交。",
  "OAuthServer.invalid_client_input": "客户端参数无效，请检查名称和回调地址。",
  "OAuthServer.client_required": "请填写客户端名称和回调地址。",
  "OAuthServer.allow_dynamic_registration": "允许动态客户端注册",
  "OAuthServer.allowed": "允许",
  "OAuthServer.apply_configuration": "应用 OAuth 配置",
  "OAuthServer.disabled": "禁用",
  "OAuthServer.dynamic_registration": "动态注册",
  "OAuthServer.enable": "启用 OAuth 服务器",
  "OAuthServer.reapply_configuration": "重新应用配置",
  "OAuthServer.signing_algorithm": "签名算法",
  "OAuthServer.service_status": "配置状态",
  "OAuthServer.configured_enabled": "已配置启用",
  "OAuthServer.not_configured_enabled": "未配置启用",
  "OAuthServer.not_configured": "未配置",
  "OAuthServer.id_token_signing": "ID Token 签名",
  "OAuthServer.runtime_unverified": "运行状态未验证，配置状态不代表 GoTrue、JWKS 或 KMS 已生效。",
  "OAuthServer.create_client": "创建客户端",
  "OAuthServer.no_clients": "尚无客户端",
  "OAuthServer.no_clients_short": "尚无客户端",
  "OAuthServer.client_created": "客户端已创建",
  "OAuthServer.client_deleted": "客户端已删除",
  "OAuthServer.client_delete_confirmation": "确认删除客户端",
  "OAuthServer.client_delete_failed": "客户端操作失败，请核对后重试。",
  "OAuthServer.endpoint_jwks": "JWKS",
  "OAuthServer.endpoint_authorization": "授权端点",
  "OAuthServer.endpoint_token": "令牌端点",
  "OAuthServer.endpoint_discovery": "授权服务器元数据",
  "OAuthServer.endpoint_oidc": "OIDC 发现端点",
  "OAuthServer.discovery_endpoints": "发现端点",
  "OAuthServer.rls_warning": "OAuth 服务器数据受 RLS 保护。",
  "OAuthServer.copy_endpoint": "复制 {label}",
  "OAuthServer.new_client_secret": "新客户端密钥",
  "OAuthServer.client_secret_one_time": "客户端密钥，仅本次返回",
  "OAuthServer.close_secret": "关闭密钥",
  "OAuthServer.copy_client_secret": "复制客户端密钥",
  "OAuthServer.not_enabled": "OAuth 尚未配置启用。",
  "OAuthServer.client_name_label": "客户端名称",
  "OAuthServer.redirect_uri_label": "回调地址",
  "OAuthServer.client_type_label": "客户端类型",
  "OAuthServer.client_auth_method_label": "客户端认证方式",
  "OAuthServer.clients_heading": "OAuth 客户端",
  "OAuthServer.clients_loading": "正在读取客户端",
  "OAuthServer.clients_unavailable": "客户端列表暂时不可用。",
  "OAuthServer.refresh_oauth": "刷新 OAuth",
  "OAuthServer.loading_oauth": "加载 OAuth",
  "OAuthServer.retry_clients": "重试客户端",
  "OAuthServer.unnamed_client": "未命名客户端",
  "OAuthServer.auth_method_missing": "认证方式未返回",
  "OAuthServer.client_state_unconfirmed": "客户端状态尚未确认",
  "Common.copy": "复制", "Common.copied": "已复制", "Common.copy_failed": "复制失败",
  "Common.delete": "删除", "Common.refresh": "刷新", "Common.retry": "重试",
};
export const t = readable((key: string, options?: { values?: Record<string, string> }) => {
  const value = translations[key] ?? key;
  return options?.values ? value.replace("{label}", options.values.label ?? "") : value;
});
