version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/management-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/edge-runtime"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/web-console"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bun"
    directory: "/packages/supacloud-js"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
