<script lang="ts">
  import { apiClient } from "$lib/api";

  import { onMount } from "svelte";
  import { page } from "$app/state";
  import { t } from "svelte-i18n";
  import { Table, Loader2, Database, Search, Plus, Trash2, Save, RefreshCw, Key, X, Check, Pencil } from "lucide-svelte";

  interface TableInfo {
    table_name: string;
    table_schema: string;
    table_type: string;
    row_estimate: number;
  }

  interface TableColumn {
    column_name: string;
    data_type: string;
    is_nullable: string;
    column_default: string | null;
    is_identity: string;
  }

  let tables = $state<TableInfo[]>([]);
  let selectedSchema = $state("public");
  let schemas = $state<string[]>(["public"]);

  // Table Management State
  let showAddTable = $state(false);
  let newTableName = $state("");
  let newTableDesc = $state("");
  let isCreatingTable = $state(false);
  let addTableError = $state<string | null>(null);

  let isLoadingSidebar = $state(true);
  let sidebarError = $state<string | null>(null);

  // Data Grid state
  let selectedTable = $state<TableInfo | null>(null);
  let tableColumns = $state<TableColumn[]>([]);
  let tableData = $state<Record<string, unknown>[]>([]);
  let isLoadingData = $state(false);
  let dataError = $state<string | null>(null);

  // Pagination
  let currentPage = $state(1);
  let pageSize = $state(50);
  let totalRows = $state(0);

  // Insert Row
  let showInsertRow = $state(false);
  let insertValues = $state<Record<string, string>>({});
  let isInserting = $state(false);
  let crudMsg = $state<string | null>(null);

  // Inline Edit
  let editingCell = $state<{ rowIdx: number; col: string } | null>(null);
  let editValue = $state("");
  let isSaving = $state(false);

  // Delete
  let isDeleting = $state(false);

  const projectRef = $derived(page.params.ref);
  const offset = $derived((currentPage - 1) * pageSize);

  // Find primary key column
  const pkColumn = $derived(
    tableColumns.find(c => c.is_identity === 'YES' || c.column_default?.includes('nextval'))?.column_name
    || tableColumns[0]?.column_name || 'id'
  );

  async function runSql(sql: string): Promise<{ rows: unknown[]; error?: string }> {
    try {
      const res = await apiClient(`/v1/projects/${projectRef}/database/sql`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sql })
      });
      const data = await res.json();
      if (data.error) return { rows: [], error: data.message || data.error };
      const rows = Array.isArray(data) ? data : data.rows || [];
      return { rows };
    } catch (err: unknown) { return { rows: [], error: (err instanceof Error ? err.message : String(err)) }; }
  }

  async function fetchSchemas() {
    const { rows } = await runSql(`SELECT DISTINCT schemaname FROM pg_tables WHERE schemaname NOT IN ('pg_catalog', 'information_schema') ORDER BY schemaname`);
    schemas = rows.map((r) => String((r as Record<string, unknown>).schemaname));
    if (schemas.length === 0) schemas = ["public"];
  }

  async function fetchTables() {
    isLoadingSidebar = true;
    sidebarError = null;
    try {
      const res = await apiClient(`/v1/projects/${projectRef}/database/sql`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sql: `SELECT table_name, table_schema, table_type,
                (SELECT reltuples::bigint FROM pg_class WHERE oid = ('"'||table_schema||'"."'||table_name||'"')::regclass) as row_estimate
               FROM information_schema.tables
               WHERE table_schema = '${selectedSchema}' AND table_type = 'BASE TABLE'
               ORDER BY table_name;`
        })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      tables = Array.isArray(data) ? data : data.rows || [];
    } catch (err: unknown) {
      sidebarError = (err instanceof Error ? err.message : String(err));
    } finally { isLoadingSidebar = false; }
  }

  async function createTable() {
    if (!newTableName) { addTableError = "表名不能为空"; return; }
    isCreatingTable = true; addTableError = null;
    try {
      const sql = `
        CREATE TABLE "${selectedSchema}"."${newTableName}" (
          id bigint generated by default as identity primary key,
          created_at timestamp with time zone default timezone('utc'::text, now()) not null
        );
        ${newTableDesc ? `COMMENT ON TABLE "${selectedSchema}"."${newTableName}" IS '${newTableDesc.replace(/'/g, "''")}';` : ''}
      `;
      const res = await apiClient(`/v1/projects/${projectRef}/database/sql`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sql })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      
      showAddTable = false;
      newTableName = ""; newTableDesc = "";
      await fetchTables();
    } catch (err: unknown) {
      addTableError = (err instanceof Error ? err.message : String(err)) || "建表失败";
    } finally {
      isCreatingTable = false;
    }
  }

  async function dropTable() {
    if (!selectedTable) return;
    if (!confirm(`警告：确定要彻底删除表 "${selectedTable.table_name}" 吗？此操作不可恢复并会删除所有数据！`)) return;
    
    try {
      const sql = `DROP TABLE "${selectedTable.table_schema}"."${selectedTable.table_name}" CASCADE;`;
      const res = await apiClient(`/v1/projects/${projectRef}/database/sql`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sql })
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      
      selectedTable = null;
      await fetchTables();
    } catch (err: unknown) {
      alert("删除失败: " + (err instanceof Error ? err.message : String(err)));
    }
  }

  async function loadTableData(tbl: TableInfo, pageNum = 1) {
    selectedTable = tbl;
    currentPage = pageNum;
    isLoadingData = true;
    dataError = null;
    totalRows = tbl.row_estimate;
    showInsertRow = false;
    editingCell = null;

    const colResult = await runSql(`SELECT column_name, data_type, is_nullable, column_default, is_identity
      FROM information_schema.columns
      WHERE table_schema = '${tbl.table_schema}' AND table_name = '${tbl.table_name}'
      ORDER BY ordinal_position`);
    if (colResult.error) { dataError = colResult.error; isLoadingData = false; return; }
    tableColumns = colResult.rows as TableColumn[];

    const off = (pageNum - 1) * pageSize;
    const dataResult = await runSql(`SELECT * FROM "${tbl.table_schema}"."${tbl.table_name}" LIMIT ${pageSize} OFFSET ${off}`);
    if (dataResult.error) { dataError = dataResult.error; isLoadingData = false; return; }
    tableData = dataResult.rows as Record<string, unknown>[];

    if (tbl.row_estimate < 100000) {
      const countResult = await runSql(`SELECT count(*) as cnt FROM "${tbl.table_schema}"."${tbl.table_name}"`);
      if (countResult.rows[0]) totalRows = parseInt(String((countResult.rows[0] as Record<string, unknown>).cnt));
    }
    isLoadingData = false;
  }

  // INSERT
  function openInsertRow() {
    insertValues = {};
    for (const col of tableColumns) {
      if (col.is_identity === 'YES' || col.column_default?.includes('nextval')) continue;
      insertValues[col.column_name] = "";
    }
    showInsertRow = true;
  }

  async function insertRow() {
    if (!selectedTable) return;
    isInserting = true;
    const cols: string[] = [];
    const vals: string[] = [];
    for (const [key, val] of Object.entries(insertValues)) {
      if (val === "" || val === undefined) continue;
      cols.push(`"${key}"`);
      vals.push(formatSqlValue(val, tableColumns.find(c => c.column_name === key)?.data_type || "text"));
    }
    if (cols.length === 0) { crudMsg = "❌ 请至少填写一个字段"; isInserting = false; setTimeout(() => crudMsg = null, 3000); return; }

    const sql = `INSERT INTO "${selectedTable.table_schema}"."${selectedTable.table_name}" (${cols.join(', ')}) VALUES (${vals.join(', ')});`;
    const { error } = await runSql(sql);
    if (error) { crudMsg = `❌ 插入失败: ${error}`; } else { crudMsg = "✅ 行已插入"; showInsertRow = false; await loadTableData(selectedTable, currentPage); }
    isInserting = false;
    setTimeout(() => crudMsg = null, 4000);
  }

  // DELETE
  async function deleteRow(row: Record<string, unknown>) {
    if (!selectedTable) return;
    const pkVal = row[pkColumn];
    if (pkVal === undefined || pkVal === null) { crudMsg = "❌ 无法确定主键值"; setTimeout(() => crudMsg = null, 3000); return; }
    if (!confirm(`确定删除 ${pkColumn} = ${pkVal} 的行吗？`)) return;
    isDeleting = true;
    const sql = `DELETE FROM "${selectedTable.table_schema}"."${selectedTable.table_name}" WHERE "${pkColumn}" = ${formatSqlValue(String(pkVal), tableColumns.find(c => c.column_name === pkColumn)?.data_type || "text")};`;
    const { error } = await runSql(sql);
    if (error) { crudMsg = `❌ 删除失败: ${error}`; } else { crudMsg = "✅ 行已删除"; await loadTableData(selectedTable, currentPage); }
    isDeleting = false;
    setTimeout(() => crudMsg = null, 4000);
  }

  // INLINE EDIT
  function startEdit(rowIdx: number, col: string, currentValue: unknown) {
    editingCell = { rowIdx, col };
    editValue = currentValue === null ? "" : String(currentValue);
  }

  function cancelEdit() { editingCell = null; editValue = ""; }

  async function saveEdit() {
    if (!editingCell || !selectedTable) return;
    const row = tableData[editingCell.rowIdx];
    const pkVal = row[pkColumn];
    if (pkVal === undefined || pkVal === null) { crudMsg = "❌ 无法确定主键值"; cancelEdit(); setTimeout(() => crudMsg = null, 3000); return; }

    isSaving = true;
    const colType = tableColumns.find(c => c.column_name === editingCell!.col)?.data_type || "text";
    const newVal = editValue === "" ? "NULL" : formatSqlValue(editValue, colType);
    const sql = `UPDATE "${selectedTable.table_schema}"."${selectedTable.table_name}" SET "${editingCell.col}" = ${newVal} WHERE "${pkColumn}" = ${formatSqlValue(String(pkVal), tableColumns.find(c => c.column_name === pkColumn)?.data_type || "text")};`;
    const { error } = await runSql(sql);
    if (error) { crudMsg = `❌ 更新失败: ${error}`; } else {
      // Update locally
      tableData[editingCell.rowIdx][editingCell.col] = editValue === "" ? null : editValue;
      crudMsg = "✅ 已更新";
    }
    cancelEdit();
    isSaving = false;
    setTimeout(() => crudMsg = null, 3000);
  }

  function formatSqlValue(val: string, dataType: string): string {
    if (val === "NULL" || val === "null") return "NULL";
    const numTypes = ["integer", "bigint", "smallint", "numeric", "real", "double precision", "serial", "bigserial"];
    const boolTypes = ["boolean"];
    if (numTypes.some(t => dataType.includes(t))) return val;
    if (boolTypes.some(t => dataType.includes(t))) return val.toLowerCase() === "true" ? "true" : "false";
    return `'${val.replace(/'/g, "''")}'`;
  }

  onMount(() => { fetchSchemas(); fetchTables(); });

  $effect(() => { if (selectedSchema) { selectedTable = null; fetchTables(); } });

  function handlePrevPage() { if (currentPage > 1 && selectedTable) loadTableData(selectedTable, currentPage - 1); }
  function handleNextPage() { if (currentPage * pageSize < totalRows && selectedTable) loadTableData(selectedTable, currentPage + 1); }
</script>

<div class="h-full flex overflow-hidden border rounded-xl bg-background shadow-sm">

  <!-- Left Sidebar -->
  <div class="w-60 flex-shrink-0 border-r border-border/50 flex flex-col bg-card/30">
    <div class="p-3 border-b border-border/50 flex flex-col gap-2">
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-2">
          <h2 class="font-semibold text-sm">{$t("Navigation.table_editor")}</h2>
          <span class="px-1.5 py-0.5 bg-brand/10 text-brand text-[10px] font-mono rounded-full font-bold">{tables.length}</span>
        </div>
        <button onclick={() => showAddTable = true} class="p-1 text-muted-foreground hover:text-foreground bg-muted hover:bg-brand/10 hover:text-brand rounded-md transition-colors" title="新建表">
          <Plus size={14} />
        </button>
      </div>
      <select bind:value={selectedSchema}
        class="w-full px-2 py-1.5 bg-background border border-border rounded-md text-xs font-mono focus:outline-none focus:ring-1 focus:ring-brand">
        {#each schemas as schema}<option value={schema}>{schema}</option>{/each}
      </select>
    </div>
    <div class="flex-1 overflow-y-auto p-2 space-y-0.5">
      {#if isLoadingSidebar}
        <div class="flex items-center justify-center py-8"><Loader2 size={16} class="animate-spin text-brand opacity-50" /></div>
      {:else if sidebarError}
        <div class="p-2 text-xs text-destructive bg-destructive/10 rounded">{sidebarError}</div>
      {:else if tables.length === 0}
        <p class="text-xs text-muted-foreground text-center py-8">{$t("Tables.no_tables")}</p>
      {:else}
        {#each tables as tbl}
          <button onclick={() => loadTableData(tbl, 1)}
            class="w-full flex items-center gap-2 px-3 py-2 text-xs rounded-md transition-colors text-left {selectedTable?.table_name === tbl.table_name ? 'bg-brand/10 text-brand font-medium' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}">
            <Table size={12} class={selectedTable?.table_name === tbl.table_name ? 'text-brand' : 'opacity-60'} />
            <span class="truncate">{tbl.table_name}</span>
          </button>
        {/each}
      {/if}
    </div>
  </div>

  <!-- Right Main Area -->
  <div class="flex-1 flex flex-col min-w-0 bg-background">
    {#if !selectedTable}
      <div class="flex-1 flex flex-col items-center justify-center text-muted-foreground gap-4">
        <Database size={48} class="opacity-10" />
        <p class="text-sm">从左侧选择一张表查看数据</p>
      </div>
    {:else}
      <!-- Toolbar -->
      <div class="h-12 border-b border-border/50 flex items-center justify-between px-4 bg-card/30 flex-shrink-0">
        <div class="flex items-center gap-3">
          <h1 class="text-sm font-bold">{selectedTable.table_name}</h1>
          <span class="text-[10px] text-muted-foreground font-mono">{selectedTable.table_schema}</span>
          <button onclick={() => loadTableData(selectedTable!, currentPage)} class="text-muted-foreground hover:text-foreground p-1 rounded hover:bg-muted transition-colors" title="刷新">
            <RefreshCw size={14} />
          </button>
        </div>
        <div class="flex gap-2">
          <button onclick={dropTable} class="px-3 py-1.5 flex items-center gap-1.5 text-[10px] font-semibold text-red-500 border border-red-500/20 bg-red-500/5 hover:bg-red-500/10 rounded-md transition-colors">
            <Trash2 size={12} /> 删除表
          </button>
          <button onclick={() => { showInsertRow = !showInsertRow; insertValues = {}; crudMsg = null; }}
            class="px-3 py-1.5 flex items-center gap-1.5 text-[10px] font-semibold text-white bg-brand hover:bg-brand/90 rounded-md transition-colors">
            <Plus size={12} /> {$t("Tables.insert_row")}
          </button>
        </div>
      </div>

      <!-- CRUD Message -->
      {#if crudMsg}
        <div class="px-4 py-1.5 text-xs font-medium {crudMsg.startsWith('✅') ? 'bg-green-500/5 text-green-700' : 'bg-red-500/5 text-red-700'}">{crudMsg}</div>
      {/if}

      <!-- Insert Row Form -->
      {#if showInsertRow}
        <div class="border-b bg-brand/5 px-4 py-3 space-y-2">
          <div class="flex items-center justify-between">
            <span class="text-xs font-semibold text-brand">新增行</span>
            <button onclick={() => showInsertRow = false} class="text-muted-foreground hover:text-foreground"><X size={14} /></button>
          </div>
          <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
            {#each tableColumns.filter(c => c.is_identity !== 'YES' && !c.column_default?.includes('nextval')) as col}
              <div>
                <span class="text-[9px] font-semibold text-muted-foreground uppercase">{col.column_name} <span class="font-normal opacity-60">{col.data_type}</span></span>
                <input type="text" bind:value={insertValues[col.column_name]}
                  placeholder={col.is_nullable === 'YES' ? 'NULL' : '必填'}
                  class="w-full mt-0.5 px-2 py-1 text-[11px] font-mono rounded border bg-background focus:outline-none focus:ring-1 focus:ring-brand" />
              </div>
            {/each}
          </div>
          <div class="flex justify-end">
            <button onclick={insertRow} disabled={isInserting}
              class="flex items-center gap-1.5 px-4 py-1.5 text-[11px] font-semibold rounded bg-brand text-white hover:bg-brand/90 disabled:opacity-50">
              {#if isInserting}<Loader2 size={12} class="animate-spin" />{:else}<Save size={12} />{/if} 插入
            </button>
          </div>
        </div>
      {/if}

      <!-- Data Grid -->
      <div class="flex-1 overflow-auto bg-muted/10 relative">
        {#if isLoadingData}
          <div class="absolute inset-0 bg-background/50 backdrop-blur-[1px] flex items-center justify-center z-10">
            <Loader2 size={32} class="animate-spin text-brand" />
          </div>
        {/if}

        {#if dataError}
          <div class="p-6">
            <div class="p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-xs font-mono">{dataError}</div>
          </div>
        {:else if tableColumns.length > 0}
          <table class="w-full text-left border-collapse min-w-max">
            <thead class="bg-card sticky top-0 z-20 shadow-sm">
              <tr>
                <th class="w-10 px-2 py-2 border-b border-r border-border/50 bg-muted/30 text-[10px] text-muted-foreground">#</th>
                {#each tableColumns as col}
                  <th class="px-3 py-2 border-b border-r border-border/50 font-medium whitespace-nowrap bg-muted/30 hover:bg-muted/50 transition-colors">
                    <div class="flex items-center gap-1.5">
                      <span class="text-[11px]">{col.column_name}</span>
                      <span class="text-[9px] font-mono text-muted-foreground/60">{col.data_type}</span>
                      {#if col.is_identity === 'YES' || col.column_default?.includes('nextval')}
                        <span title="主键"><Key size={9} class="text-amber-500" /></span>
                      {/if}
                    </div>
                  </th>
                {/each}
                <th class="w-10 px-2 py-2 border-b border-border/50 bg-muted/30"></th>
              </tr>
            </thead>
            <tbody class="divide-y divide-border/20">
              {#if tableData.length === 0 && !isLoadingData}
                <tr>
                  <td colspan={tableColumns.length + 2} class="px-4 py-12 text-center text-muted-foreground text-sm">表中暂无数据</td>
                </tr>
              {:else}
                {#each tableData as row, i}
                  <tr class="hover:bg-muted/30 group transition-colors">
                    <td class="w-10 px-2 py-1.5 border-r border-border/20 text-center text-[10px] text-muted-foreground font-mono bg-muted/10">{offset + i + 1}</td>
                    {#each tableColumns as col}
                      <td class="px-3 py-1.5 border-r border-border/20 text-[11px] font-mono max-w-[280px]"
                        ondblclick={() => startEdit(i, col.column_name, row[col.column_name])}>
                        {#if editingCell?.rowIdx === i && editingCell?.col === col.column_name}
                          <div class="flex items-center gap-1">
                            <input type="text" bind:value={editValue}
                              onkeydown={(e) => { if (e.key === 'Enter') saveEdit(); if (e.key === 'Escape') cancelEdit(); }}
                              class="flex-1 px-1 py-0.5 text-[11px] font-mono rounded border border-brand bg-background focus:outline-none min-w-[60px]"
 />
                            <button onclick={saveEdit} disabled={isSaving} class="p-0.5 text-green-600 hover:bg-green-500/10 rounded"><Check size={12} /></button>
                            <button onclick={cancelEdit} class="p-0.5 text-muted-foreground hover:bg-muted rounded"><X size={12} /></button>
                          </div>
                        {:else}
                          <span class="cursor-pointer hover:bg-brand/5 px-1 rounded transition-colors truncate block" title="双击编辑">
                            {#if row[col.column_name] === null}
                              <span class="text-muted-foreground/40 italic">NULL</span>
                            {:else if typeof row[col.column_name] === 'boolean'}
                              <span class={row[col.column_name] ? 'text-green-600' : 'text-red-600'}>{String(row[col.column_name])}</span>
                            {:else if typeof row[col.column_name] === 'object'}
                              <span class="text-blue-600">{JSON.stringify(row[col.column_name])}</span>
                            {:else}
                              {String(row[col.column_name])}
                            {/if}
                          </span>
                        {/if}
                      </td>
                    {/each}
                    <td class="w-10 px-1.5 py-1 text-center">
                      <button onclick={() => deleteRow(row)}
                        class="p-1 rounded text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors opacity-0 group-hover:opacity-100"
                        title="删除行" disabled={isDeleting}>
                        <Trash2 size={12} />
                      </button>
                    </td>
                  </tr>
                {/each}
              {/if}
            </tbody>
          </table>
        {/if}
      </div>

      <!-- Pagination -->
      <div class="h-10 border-t border-border/50 flex items-center justify-between px-4 bg-card flex-shrink-0 text-xs text-muted-foreground">
        <div class="flex items-center gap-3">
          <span>{totalRows} 条记录</span>
          {#if totalRows > 0}
            <span class="font-mono">第 {offset + 1}-{Math.min(offset + pageSize, totalRows)} 条</span>
          {/if}
        </div>
        <div class="flex items-center gap-2">
          <button onclick={handlePrevPage} disabled={currentPage === 1 || isLoadingData}
            class="px-2 py-1 rounded hover:bg-muted disabled:opacity-30 transition-colors">上一页</button>
          <span class="font-mono bg-muted/50 px-2 py-0.5 rounded">第 {currentPage} 页</span>
          <button onclick={handleNextPage} disabled={currentPage * pageSize >= totalRows || isLoadingData}
            class="px-2 py-1 rounded hover:bg-muted disabled:opacity-30 transition-colors">下一页</button>
        </div>
      </div>
    {/if}
  </div>
</div>

<!-- Add Table Modal -->
{#if showAddTable}
  <div class="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center">
    <div class="bg-card w-full max-w-md rounded-xl border shadow-lg overflow-hidden flex flex-col">
      <div class="px-5 py-4 border-b flex items-center justify-between">
        <h3 class="font-bold">新建表</h3>
        <button onclick={() => showAddTable = false} class="text-muted-foreground hover:text-foreground p-1 rounded-md">
          <X size={16} />
        </button>
      </div>
      <div class="p-5 space-y-4">
        {#if addTableError}
          <div class="p-2 border border-red-500/20 bg-red-500/10 text-red-600 text-xs rounded">{addTableError}</div>
        {/if}
        <div>
          <span class="text-xs text-muted-foreground font-semibold">表名 (Name)</span>
          <input type="text" bind:value={newTableName} placeholder="如：users, posts" 
            class="w-full mt-1.5 px-3 py-2 text-sm rounded-lg border bg-background focus:outline-none focus:ring-1 focus:ring-brand font-mono" />
        </div>
        <div>
          <span class="text-xs text-muted-foreground font-semibold">描述 (Description)</span>
          <textarea bind:value={newTableDesc} placeholder="可选的表注释" rows="2"
            class="w-full mt-1.5 px-3 py-2 text-sm rounded-lg border bg-background focus:outline-none focus:ring-1 focus:ring-brand"></textarea>
        </div>
        <div class="p-3 bg-muted/30 rounded-lg border border-border/50">
          <p class="text-[10px] text-muted-foreground leading-relaxed">
            新建表会自动包含以下基础列：<br/>
            <span class="font-mono font-medium text-foreground">id</span> (int8, primary key, identity)<br/>
            <span class="font-mono font-medium text-foreground">created_at</span> (timestamptz, default now())
          </p>
        </div>
      </div>
      <div class="px-5 py-4 bg-muted/10 border-t flex justify-end gap-3">
        <button onclick={() => showAddTable = false} class="px-4 py-2 text-xs font-medium rounded-lg hover:bg-muted/50 transition-colors">取消</button>
        <button onclick={createTable} disabled={isCreatingTable || !newTableName} 
          class="flex items-center gap-2 px-4 py-2 text-xs font-semibold rounded-lg bg-brand text-white hover:bg-brand/90 transition-colors disabled:opacity-50">
          {#if isCreatingTable}<Loader2 size={12} class="animate-spin" />{/if}
          确认创建
        </button>
      </div>
    </div>
  </div>
{/if}
