import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { rm } from "node:fs/promises";
import { JSDOM } from "jsdom";
import { compile, compileModule, preprocess } from "svelte/compiler";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import { createAuthUrlConfigClient } from "../../../../../lib/auth-url-config";

const localFile = (path: string) => fileURLToPath(new URL(path, import.meta.url));
const input = { site_url: "https://app.test", uri_allow_list: "https://app.test/**" };

test("URL schemas and validation remain identical to the backend", () => {
  for (const [source, generated] of [
    ["contracts/auth-url-config.ts", "auth-url-config.ts"],
    ["utils/auth-url-config.ts", "auth-url-validation.ts"],
  ]) {
    expect(readFileSync(localFile(`../../../../../lib/generated/${generated}`), "utf8")).toBe(
      "// Generated by scripts/generate-auth-url-config-contract.mjs. Do not edit.\n"
      + readFileSync(localFile(`../../../../../../../management-api/src/${source}`), "utf8")
        .replace('"../contracts/auth-url-config"', '"./auth-url-config"'),
    );
  }
});

test("typed URL forms reject undeclared fields and wrong input/result types", () => {
  const result = Bun.spawnSync([
    "./node_modules/.bin/tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck",
    "--module", "esnext", "--moduleResolution", "bundler", "--target", "es2023",
    "--lib", "esnext,dom,dom.iterable", "src/lib/auth-url-config.typecheck.ts",
  ], { cwd: localFile("../../../../../../") });
  expect(new TextDecoder().decode(result.stdout) + new TextDecoder().decode(result.stderr)).toBe("");
  expect(result.exitCode).toBe(0);
}, 30_000);

test("SVAdmin snapshots writable fields before normalization and sends one canonical PATCH", async () => {
  const writes: { url: string; body: unknown }[] = [];
  const client = createAuthUrlConfigClient("tenant-a", async (url, options) => {
    writes.push({ url, body: JSON.parse(String(options?.body)) });
    return Response.json({ ...input, private_key: "not-exposed" });
  });
  expect(await client.update({ site_url: " https://app.test ", uri_allow_list: " https://app.test/** " }))
    .toEqual({ siteUrl: input.site_url, redirectUrls: [input.uri_allow_list] });
  expect(writes).toEqual([{ url: "/v1/projects/tenant-a/auth/config", body: input }]);
  let getterCalls = 0;
  await expect(client.update({ ...input, get site_url() { getterCalls++; return input.site_url; } })).rejects.toThrow();
  await expect(client.update({ ...input, secret: "no" })).rejects.toThrow();
  await expect(client.update({ ...input, toJSON() { getterCalls++; return input; } })).rejects.toThrow();
  await expect(client.update({ ...input, site_url: "javascript:alert(1)" })).rejects.toThrow();
  await expect(client.update({ ...input, uri_allow_list: "https://name:pass@app.test" })).rejects.toThrow();
  await expect(client.update({ ...input, uri_allow_list: "https://app.test,," })).rejects.toThrow();
  expect(getterCalls).toBe(0);
  expect(writes).toHaveLength(1);
});

test.each([
  {}, { site_url: input.site_url }, { ...input, site_url: 2 },
  { ...input, uri_allow_list: "" }, { ...input, SITE_URL: "https://foreign.test" },
  { ...input, success: false },
  { ...input, uri_allow_list: `${input.uri_allow_list},,` },
  { ...input, uri_allow_list: ` ${input.uri_allow_list} ` },
])("malformed or mismatched receipts never confirm a write", async payload => {
  let sends = 0;
  const client = createAuthUrlConfigClient("tenant-a", async () => { sends++; return Response.json(payload); });
  await expect(client.update(input)).rejects.toThrow();
  expect(sends).toBe(1);
});

test("cancellation and persisted runtime failures cannot produce success or replay", async () => {
  const response = Promise.withResolvers<Response>();
  let sends = 0;
  const client = createAuthUrlConfigClient("tenant-a", async () => { sends++; return response.promise; });
  const controller = new AbortController();
  const pending = client.update(input, controller.signal);
  controller.abort();
  response.resolve(Response.json(input));
  await expect(pending).rejects.toThrow();
  await expect(client.update(input, controller.signal)).rejects.toThrow();
  expect(sends).toBe(1);
  const failed = createAuthUrlConfigClient("tenant-a", async () =>
    Response.json({ persisted: true, message: "runtime unavailable" }, { status: 503 }));
  await expect(failed.update(input)).rejects.toThrow("runtime unavailable");
});

test("read boundary validates legacy fields and rejects malformed documents", async () => {
  const legacy = createAuthUrlConfigClient("tenant-a", async () => Response.json({
    SITE_URL: input.site_url, URI_ALLOW_LIST: input.uri_allow_list, secret: "not-exposed",
  }));
  expect(await legacy.read()).toEqual({ siteUrl: input.site_url, redirectUrls: [input.uri_allow_list] });
  const invalid = createAuthUrlConfigClient("tenant-a", async () => Response.json({ uri_allow_list: [] }));
  await expect(invalid.read()).rejects.toThrow();
});

test("compiled URL page isolates drafts, retries and A-B-A late results", async () => {
  if (process.env.SUPACLOUD_URL_CONFIG_TEST !== "1") {
    const child = Bun.spawn({
      cmd: [process.execPath, "test", fileURLToPath(import.meta.url), "-t", "compiled URL page"],
      env: { ...process.env, SUPACLOUD_URL_CONFIG_TEST: "1" }, stdout: "pipe", stderr: "pipe",
    });
    const [exitCode, stdout, stderr] = await Promise.all([
      child.exited, new Response(child.stdout).text(), new Response(child.stderr).text(),
    ]);
    expect(exitCode, `${stdout}\n${stderr}`).toBe(0);
    return;
  }
  const dom = new JSDOM("<!doctype html><html><body></body></html>", { pretendToBeVisual: true, url: "http://localhost/" });
  const w = dom.window;
  Object.assign(globalThis, {
    window: w, document: w.document, navigator: w.navigator, HTMLElement: w.HTMLElement,
    HTMLInputElement: w.HTMLInputElement, HTMLButtonElement: w.HTMLButtonElement,
    Element: w.Element, Node: w.Node, Text: w.Text, Comment: w.Comment, Event: w.Event,
    CustomEvent: w.CustomEvent, MouseEvent: w.MouseEvent, MutationObserver: w.MutationObserver,
    getComputedStyle: w.getComputedStyle.bind(w),
    requestAnimationFrame: w.requestAnimationFrame.bind(w), cancelAnimationFrame: w.cancelAnimationFrame.bind(w),
  });
  const path = join(tmpdir(), `supacloud-url-config-${crypto.randomUUID()}.mjs`);
  const ts = new Bun.Transpiler({ loader: "ts" });
  try {
    const result = await Bun.build({
      entrypoints: [localFile("page.test-entry.ts")], target: "browser", format: "esm",
      conditions: ["svelte", "browser"], external: ["node:assert"],
      plugins: [{ name: "url-config-tests", setup(builder) {
        builder.onResolve({ filter: /^\$app\/state$/ }, () => ({ path: localFile("../settings.test-state.svelte.ts") }));
        builder.onResolve({ filter: /^\$lib\/auth-url-config$/ }, () => ({ path: localFile("../../../../../lib/auth-url-config.ts") }));
        builder.onResolve({ filter: /^svelte-i18n$/ }, () => ({ path: "i18n", namespace: "fixture" }));
        builder.onLoad({ filter: /.*/, namespace: "fixture" }, () => ({
          contents: "export const t = { subscribe(run) { run(key => key); return () => {}; } };", loader: "js",
        }));
        builder.onLoad({ filter: /\.svelte$/ }, async ({ path }) => {
          const source = await preprocess(await Bun.file(path).text(), vitePreprocess(), { filename: path });
          return { contents: compile(source.code, { filename: path, generate: "client", css: "injected" }).js.code, loader: "js" };
        });
        builder.onLoad({ filter: /\.svelte\.[jt]s$/ }, async ({ path }) => ({
          contents: compileModule(ts.transformSync(await Bun.file(path).text()), { filename: path, generate: "client" }).js.code,
          loader: "js",
        }));
      } }],
    });
    if (!result.success || !result.outputs[0]) throw new AggregateError(result.logs, "URL page fixture build failed");
    await Bun.write(path, result.outputs[0]);
    await import(pathToFileURL(path).href);
  } finally {
    await rm(path, { force: true });
    dom.window.close();
  }
}, 30_000);
