#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import secrets
from datetime import datetime, timedelta, timezone
from urllib.parse import urlparse


def b64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode("ascii")


def jwt_encode(secret: str, payload: dict[str, object]) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    signing_input = (
        f"{b64url(json.dumps(header, separators=(',', ':')).encode())}."
        f"{b64url(json.dumps(payload, separators=(',', ':')).encode())}"
    )
    signature = hmac.new(
        secret.encode("utf-8"),
        signing_input.encode("ascii"),
        hashlib.sha256,
    ).digest()
    return f"{signing_input}.{b64url(signature)}"


def derive_base_domain(public_url: str) -> str:
    host = urlparse(public_url).hostname or "localhost"
    if host in {"localhost", "127.0.0.1"}:
        return "localhost"
    if host.startswith("api."):
        return host[4:]
    return host


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate docker/self-host/.env for SupaCloud",
    )
    parser.add_argument(
        "--public-url",
        default="http://localhost:8000",
        help="External API/Kong URL",
    )
    parser.add_argument(
        "--studio-url",
        default="http://localhost:9090",
        help="External Studio/console URL",
    )
    parser.add_argument(
        "--postgres-password",
        default=secrets.token_urlsafe(18),
        help="Postgres superuser password",
    )
    parser.add_argument(
        "--jwt-secret",
        default=secrets.token_urlsafe(32),
        help="JWT signing secret",
    )
    parser.add_argument(
        "--master-token",
        default=secrets.token_urlsafe(32),
        help="Management API master token",
    )
    parser.add_argument(
        "--secrets-encryption-key",
        default=secrets.token_urlsafe(32),
        help="Management API secret encryption key",
    )
    parser.add_argument(
        "--timezone",
        default="Asia/Shanghai",
        help="Container timezone",
    )
    args = parser.parse_args()

    now = datetime.now(timezone.utc)
    issued_at = int(now.timestamp())
    expires_at = int((now + timedelta(days=3650)).timestamp())

    anon_key = jwt_encode(
        args.jwt_secret,
        {
            "role": "anon",
            "iss": "supabase",
            "iat": issued_at,
            "exp": expires_at,
        },
    )
    service_role_key = jwt_encode(
        args.jwt_secret,
        {
            "role": "service_role",
            "iss": "supabase",
            "iat": issued_at,
            "exp": expires_at,
        },
    )

    print("# Generated by docker/self-host/init-env.py")
    print(f"# Generated at {now.isoformat()}")
    print(f"TZ={args.timezone}")
    print("POSTGRES_USER=postgres")
    print(f"POSTGRES_PASSWORD={args.postgres_password}")
    print("POSTGRES_DB=postgres")
    print("POSTGRES_PORT=5432")
    print(f"JWT_SECRET={args.jwt_secret}")
    print(f"ANON_KEY={anon_key}")
    print(f"SERVICE_ROLE_KEY={service_role_key}")
    print(f"MASTER_TOKEN={args.master_token}")
    print(f"SECRETS_ENCRYPTION_KEY={args.secrets_encryption_key}")
    print(f"PUBLIC_URL={args.public_url}")
    print(f"STUDIO_URL={args.studio_url}")
    print(f"BASE_DOMAIN={derive_base_domain(args.public_url)}")
    print("PGRST_DB_SCHEMAS=public,storage,graphql_public")
    print("KONG_HTTP_PORT=8000")
    print("KONG_HTTPS_PORT=8443")
    print("KONG_ADMIN_PORT=8001")
    print("API_PORT=9090")
    print("EDGE_RUNTIME_PORT=9000")


if __name__ == "__main__":
    main()
