import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createAuthUserClient } from "./auth-user-mutations";
import { apiClient, type ApiRequestInit } from "./api";

const root = new URL("../../../", import.meta.url);

test("browser mutation contracts match the backend source exactly", () => {
  const source = readFileSync(new URL("management-api/src/contracts/auth-user-mutations.ts", root), "utf8");
  const generated = readFileSync(new URL("./generated/auth-user-mutations.ts", import.meta.url), "utf8");
  expect(generated).toBe("// Generated by scripts/generate-auth-user-contract.mjs. Do not edit.\n" + source);
  const route = readFileSync(new URL("management-api/src/routes/auth-users.ts", root), "utf8");
  expect(route).toContain("body: createAuthUserSchema");
  expect(route).toContain("body: inviteAuthUserSchema");
  expect(route.match(/Value\.Check\(authUserResultSchema, result\)/g)).toHaveLength(2);
});

test("form input and result types are inferred and reject unsupported fields", () => {
  const result = Bun.spawnSync([
    "./node_modules/.bin/tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck",
    "--module", "esnext", "--moduleResolution", "bundler", "--target", "es2023",
    "--lib", "esnext,dom,dom.iterable", "src/lib/auth-user-mutations.typecheck.ts",
  ], { cwd: fileURLToPath(new URL("../../", import.meta.url)) });
  expect(new TextDecoder().decode(result.stdout) + new TextDecoder().decode(result.stderr)).toBe("");
  expect(result.exitCode).toBe(0);
}, 30_000);

test("fixed tenant routes send typed forms once and decode user results", async () => {
  const requests: { url: string; options: ApiRequestInit }[] = [];
  const client = createAuthUserClient("tenant-a", async (url, options = {}) => {
    requests.push({ url, options });
    return Response.json({ id: "user-1", email: "user@example.test", identities: [] });
  });
  const input = { email: "user@example.test", password: "secret", email_confirm: true };
  expect((await client.create(input)).id).toBe("user-1");
  await client.invite({ email: input.email });
  expect(requests.map(item => item.url)).toEqual([
    "/v1/projects/tenant-a/auth/users", "/v1/projects/tenant-a/auth/users/invite",
  ]);
  expect(JSON.parse(String(requests[0]?.options.body))).toEqual(input);
  expect(requests.every(item => item.options.method === "POST")).toBe(true);
});

test("unknown fields and invalid inputs are rejected before transport", async () => {
  let sends = 0;
  const client = createAuthUserClient("tenant-a", async () => {
    sends++;
    return Response.json({ id: "user-1" });
  });
  const privileged = { email: "user@example.test", app_metadata: { role: "admin" } };
  await expect(client.invite(privileged)).rejects.toThrow("Invalid auth user input");
  // @ts-expect-error Exercise untyped external callers.
  await expect(client.create({ email: "user@example.test" })).rejects.toThrow();
  expect(sends).toBe(0);
  expect(() => createAuthUserClient("../other")).toThrow("Invalid project reference");
});

test.each([
  () => Response.json({ success: false, message: "Denied" }),
  () => Response.json({ email: "user@example.test" }),
  () => Response.json({ id: 123 }),
  () => Response.json({ id: "" }),
  () => new Response(null, { status: 204 }),
  () => new Response("<html>error</html>"),
  () => Response.json({ message: "Forbidden" }, { status: 403 }),
])("invalid or rejected responses never report success or retry", async response => {
  let sends = 0;
  const client = createAuthUserClient("tenant-a", async () => { sends++; return response(); });
  await expect(client.invite({ email: "user@example.test" })).rejects.toThrow();
  expect(sends).toBe(1);
});

test("cancellation prevents dispatch and rejects late results without replay", async () => {
  const controller = new AbortController();
  let sends = 0;
  const response = Promise.withResolvers<Response>();
  const client = createAuthUserClient("tenant-a", async () => { sends++; return response.promise; });
  const pending = client.invite({ email: "user@example.test" }, controller.signal);
  controller.abort();
  response.resolve(Response.json({ id: "user-1" }));
  await expect(pending).rejects.toThrow();
  await expect(client.invite({ email: "user@example.test" }, controller.signal)).rejects.toThrow();
  expect(sends).toBe(1);
});

test("real Studio transport retains credentials and does not replay lost writes", async () => {
  const original = globalThis.fetch;
  const requests: RequestInit[] = [];
  globalThis.fetch = Object.assign(async (_input: RequestInfo | URL, options?: RequestInit) => {
    requests.push(options ?? {});
    throw new TypeError("Response lost after dispatch");
  }, { preconnect: original.preconnect });
  try {
    const client = createAuthUserClient("tenant-a", apiClient);
    await expect(client.invite({ email: "user@example.test" })).rejects.toThrow("Response lost");
    expect(requests).toHaveLength(1);
    expect(requests[0]?.credentials).toBe("include");
    expect(requests[0]?.redirect).toBe("error");
  } finally {
    globalThis.fetch = original;
  }
});
