import { Elysia } from "elysia";
import { swagger } from "@elysiajs/swagger";
import { cors } from "@elysiajs/cors";

try {
  const envFile = Bun.file('/opt/supacloud/config.env');
  if (envFile.size > 0) {
    const text = await envFile.text();
    const matches = text.matchAll(/^([A-Z0-9_]+)="?(.*?)"?$/gm);
    for (const match of matches) {
      if (!process.env[match[1]]) process.env[match[1]] = match[2];
    }
  }
} catch (e) {
  // Ignore
}

import { config } from "./config";
import { authMiddleware } from "./middleware/auth";
import { closeDb } from "./db";
import { studioRoutes, studioAuthRoutes, studioV1Routes } from "./routes";

const app = new Elysia({ strictPath: false })
  // Swagger docs
  .use(
    swagger({
      documentation: {
        info: {
          title: "SupaCloud Management API",
          version: "1.0.0",
          description: "API for managing SupaCloud multi-tenant projects",
        },
        tags: [
          { name: "projects", description: "Project management endpoints" },
          { name: "organizations", description: "Organization management endpoints" },
          { name: "user", description: "User profile endpoints" },
          { name: "backups", description: "Database backup and restore endpoints" },
          { name: "monitor", description: "Database monitoring and health endpoints" },
          { name: "maintenance", description: "High availability and cluster maintenance" },
          { name: "extensions", description: "PostgreSQL extension management (Market)" },
          { name: "security", description: "Firewall and SSL security management" },
          { name: "storage", description: "JuiceFS storage and S3 migration management" },
          { name: "scaling", description: "Auto-scaling and vertical upgrade management" },
          { name: "tasks", description: "Background task monitoring" },
          { name: "auth", description: "Authentication and OAuth provider management" },
          { name: "frontend", description: "Frontend hosting and deployment management" },
          { name: "webhook", description: "GitHub webhook and CI/CD integration" },
        ],
        components: {
          securitySchemes: {
            bearerAuth: {
              type: "http",
              scheme: "bearer",
            },
          },
        },
        security: [{ bearerAuth: [] }],
      },
    })
  )
  // CORS
  .use(cors())

  // Health check (no auth required)
  .get("/health", () => ({ status: "ok", timestamp: new Date().toISOString() }))

  // Studio Compatibility Layer (mounted BEFORE main routes to override)
  // This ensures /api/platform/* and /api/v1/* Studio-specific routes take precedence
  .group("/api", (api) =>
    api
      .use(studioRoutes)
      .use(studioAuthRoutes)
      .use(studioV1Routes)
  )
  // Direct mounting for internal access
  .use(studioRoutes)
  .use(studioAuthRoutes)
  .use(studioV1Routes)

  // Main API Routes (mounted after Studio routes)
  .use(await registerAllRoutes())

  // API version info
  .get("/", () => ({
    name: "SupaCloud Management API",
    version: "1.0.0",
    docs: "/swagger",
  }))

  // Dashboard & SPA Assets (catch-all for everything else)
  .use(registerStaticAssets())

  // Monitoring and diagnostic endpoints
  .get("/monitor/health", async () => {
    const { HealthChecker } = await import("./infra/health");
    return await HealthChecker.runFullCheck();
  })

  // Error handling
  .onError(({ code, error, set }) => {
    console.error(`Error [${code}]:`, error);

    if (code === "VALIDATION") {
      set.status = 400;
      return { error: "Validation failed", details: error.message };
    }

    if (code === "NOT_FOUND") {
      set.status = 404;
      return { error: "Not found" };
    }

    set.status = 500;
    return { error: "Internal server error" };
  });

// @ts-ignore: This file is auto-generated by scripts/pack-assets.ts
import { EMBEDDED_ASSETS } from "./assets.gen";

const WEB_CONSOLE_DIR = process.env.WEB_CONSOLE_DIR || "/opt/supacloud/packages/web-console/build";

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

/**
 * Register static assets (SPA)
 */
export function registerStaticAssets() {
  return new Elysia({ name: "static-assets" }).get("*", async (context) => {
    const { request, set } = context;
    const url = new URL(request.url);
    const path = url.pathname === "/" ? "/index.html" : url.pathname;

    // Do NOT catch API routes in static assets
    if (path.startsWith("/api/") || path.startsWith("/v1/") || path.startsWith("/platform/")) {
      set.status = 404;
      return { error: "Route not found" };
    }

    // Try to serve from file system first (web-console build)
    try {
      const fs = await import("fs");
      const filePath = `${WEB_CONSOLE_DIR}${path}`;

      if (fs.existsSync(filePath)) {
        const stat = fs.statSync(filePath);
        if (stat.isFile()) {
          const ext = path.substring(path.lastIndexOf("."));
          set.headers["Content-Type"] = MIME_TYPES[ext] || "application/octet-stream";
          return fs.readFileSync(filePath);
        }
      }

      // Try index.html for SPA routing
      const indexPath = `${WEB_CONSOLE_DIR}/index.html`;
      if (fs.existsSync(indexPath) && !path.includes(".")) {
        set.headers["Content-Type"] = "text/html";
        return fs.readFileSync(indexPath);
      }
    } catch (e) {
      // Fall through to embedded assets
    }

    // Fall back to embedded assets
    try {
      const ASSETS = EMBEDDED_ASSETS;
      let asset = ASSETS[path];
      if (!asset && !path.includes(".")) {
        asset = ASSETS["/index.html"];
      }

      if (asset) {
        set.headers["Content-Type"] = asset.mimeType as string;
        return Buffer.from(asset.content, 'base64');
      } else {
        set.status = 404;
        return "Internal Asset Not Found.";
      }
    } catch (e) {
      if (process.env.NODE_ENV !== "production") {
        return "Management Console DEV mode: run 'bun run build:all' to load SPA assets into memory.";
      }
      set.status = 404;
      return "App Assets Not Built.";
    }
  });
}

/**
 * Register all route modules
 */
export async function registerAllRoutes() {
  const {
    projectRoutes, organizationRoutes, userRoutes, backupRoutes,
    monitorRoutes, maintenanceRoutes, extensionRoutes, securityRoutes,
    storageRoutes, scalingRoutes, taskRoutes, databaseRoutes, authRoutes,
    frontendRoutes, webhookRoutes
  } = await import("./routes");

  return new Elysia({ name: "api-routes" })
    .use(authMiddleware)
    .use(projectRoutes)
    .use(organizationRoutes)
    .use(userRoutes)
    .use(backupRoutes)
    .use(monitorRoutes)
    .use(maintenanceRoutes)
    .use(extensionRoutes)
    .use(securityRoutes)
    .use(storageRoutes)
    .use(scalingRoutes)
    .use(taskRoutes)
    .use(databaseRoutes)
    .use(authRoutes)
    .use(frontendRoutes)
    .use(webhookRoutes);
}

const args = process.argv.slice(2);

/**
 * Core logic: Based on command line arguments, decide whether to execute a single task or start the API server.
 */
async function bootstrap() {
  if (args.includes("--init-db")) {
    const { initDatabase } = await import("./db/init");
    try {
      await initDatabase();
      console.log("Database initialized successfully!");
      process.exit(0);
    } catch (err) {
      console.error("Failed to initialize database:", err);
      process.exit(1);
    }
  } else if (args.includes("install") || args.includes("--install")) {
    const { runInstall } = await import("./install");
    const forceYes = args.includes("--yes") || args.includes("-y");
    try {
      await runInstall({ forceYes });
      process.exit(0);
    } catch (err) {
      console.error("Installation aborted:", err);
      process.exit(1);
    }
  } else if (args.includes("upgrade") || args.includes("--upgrade")) {
    const { runUpgrade } = await import("./upgrade");
    const forceYes = args.includes("--yes") || args.includes("-y");
    try {
      await runUpgrade({ forceYes });
      process.exit(0);
    } catch (err) {
      console.error("Upgrade aborted:", err);
      process.exit(1);
    }
  } else if (args.includes("doctor") || args.includes("--doctor")) {
    const { runDoctor } = await import("./doctor");
    const skipSmokeTest = args.includes("--skip-smoke-test");
    const forceYes = args.includes("--yes") || args.includes("-y");
    try {
      await runDoctor({ skipSmokeTest, forceYes });
      process.exit(0);
    } catch (err) {
      console.error("Doctor scan failed:", err);
      process.exit(1);
    }
  } else if (args.includes("start") || args.includes("up")) {
    const { handleStart } = await import("./cli/lifecycle");
    await handleStart();
    process.exit(0);
  } else if (args.includes("stop") || args.includes("down")) {
    const { handleStop } = await import("./cli/lifecycle");
    await handleStop();
    process.exit(0);
  } else if (args.includes("status") || args.includes("check")) {
    const { handleStatus } = await import("./cli/lifecycle");
    await handleStatus();
    process.exit(0);
  } else if (args[0] === "logs") {
    const { handleLogs } = await import("./cli/lifecycle");
    const serviceTarget = args[1] && !args[1].startsWith("-") ? args[1] : undefined;
    await handleLogs(serviceTarget);
    process.exit(0);
  } else if (args[0] === "project") {
    const { handleProjectCreate, handleProjectList, handleProjectGet, handleProjectDelete,
      handleProjectPause, handleProjectRestore, handleProjectRestart,
      handleProjectKeys, handleProjectRotateKeys, printProjectHelp } = await import("./cli/project");
    const subCommand = args[1];
    switch (subCommand) {
      case "create":
        await handleProjectCreate(args.slice(2));
        break;
      case "list":
      case "ls":
        await handleProjectList();
        break;
      case "get":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectGet(args[2]);
        break;
      case "delete":
      case "rm":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectDelete(args[2], args.slice(3));
        break;
      case "pause":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectPause(args[2]);
        break;
      case "restore":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectRestore(args[2]);
        break;
      case "restart":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectRestart(args[2]);
        break;
      case "keys":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectKeys(args[2]);
        break;
      case "rotate-keys":
        if (!args[2]) {
          console.error("Error: project ref required");
          printProjectHelp();
          process.exit(1);
        }
        await handleProjectRotateKeys(args[2], args.slice(3));
        break;
      case "--help":
      case "-h":
      default:
        printProjectHelp();
        process.exit(0);
    }
    process.exit(0);
  } else if (args.includes("--version") || args.includes("-v")) {
    const pkg = await import("../package.json");
    console.log(`SupaCloud Version: ${pkg.version}`);
    process.exit(0);
  } else if (args.includes("--help") || args.includes("-h")) {
    process.exit(0);
  } else if (args.length === 0 || args.includes("--server")) {
    app.listen(config.port);
    const { taskWorker } = await import("./services/task.worker");
    taskWorker.start();

    console.log(`
    ╔═══════════════════════════════════════════════════════════╗
    ║          SupaCloud Management API                         ║
    ╠═══════════════════════════════════════════════════════════╣
    ║  Server running at: http://localhost:${config.port}                ║
    ║  Swagger docs at:   http://localhost:${config.port}/swagger        ║
    ╚═══════════════════════════════════════════════════════════╝
    `);
  } else {
    console.error(`Unknown command or argument: ${args.join(" ")}`);
    process.exit(1);
  }
}

if (import.meta.main) {
  bootstrap();

  const shutdown = async (signal: string) => {
    console.log(`\nReceived ${signal}. Gracefully shutting down...`);
    try {
      const { taskWorker } = await import("./services/task.worker");
      taskWorker.stop();
    } catch { }

    try {
      await closeDb();
      console.log("Database connections released.");
    } catch { }

    process.exit(0);
  };

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));
}

export { app };
