import { createHash } from "node:crypto";
import { mkdir, readFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import * as ts from "@typescript/typescript6";
import { renderGraphql } from "./graphql";
import { writeFileIfChanged } from "./generate";
import { assertGraphqlOptions } from "./graphql-options";
import type { GraphqlOptions } from "./types";

export interface DatabaseContractsOptions {
  rootDir: string;
  outDir: string;
  /** Generated by the official Supabase/Postgres Meta exporter, not a handwritten table map. */
  postgrestTypes: string;
  /** Source module defining Drizzle tables; imported as types, never executed by this generator. */
  drizzleSchema: string;
  /** Explicit identity/role label for reviewing snapshot provenance. Not an authorization proof. */
  role: string;
  graphql: GraphqlOptions;
  /** Ordered complete migration history. */
  migrations: readonly string[];
}

function hash(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}
function importPath(out: string, path: string): string {
  const value = relative(out, path).replaceAll("\\", "/").replace(/\.(?:d\.)?[cm]?ts$/, "");
  return value.startsWith(".") ? value : `./${value}`;
}

export function parseDatabaseContractsOptions(value: unknown, directory: string): DatabaseContractsOptions {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Expected database contracts configuration");
  const allowed = ["rootDir", "outDir", "postgrestTypes", "drizzleSchema", "role", "graphql", "migrations"];
  if (Object.keys(value).some((name) => !allowed.includes(name))) throw new TypeError("Unknown database contracts option");
  const field = (name: string) => {
    const result: unknown = Reflect.get(value, name);
    if (typeof result !== "string" || !result.trim()) throw new TypeError(`Missing database contracts ${name}`);
    return result;
  };
  const graphql: unknown = Reflect.get(value, "graphql");
  assertGraphqlOptions(graphql);
  const migrations: unknown = Reflect.get(value, "migrations");
  if (!Array.isArray(migrations) || !migrations.every((entry): entry is string => typeof entry === "string" && entry.endsWith(".sql"))) {
    throw new TypeError("migrations must be an ordered list of SQL files");
  }
  return {
    rootDir: resolve(directory, field("rootDir")), outDir: resolve(directory, field("outDir")),
    postgrestTypes: resolve(directory, field("postgrestTypes")), drizzleSchema: resolve(directory, field("drizzleSchema")),
    role: field("role"), graphql: { ...graphql, schema: resolve(directory, graphql.schema) },
    migrations: migrations.map((file) => resolve(directory, file)),
  };
}

/** One offline entrypoint; preserves each protocol's native type semantics and generated validators. */
export async function generateDatabaseContracts(options: DatabaseContractsOptions, check = false) {
  const rootDir = resolve(options.rootDir), outDir = resolve(options.outDir);
  const postgrestTypes = resolve(rootDir, options.postgrestTypes), drizzleSchema = resolve(rootDir, options.drizzleSchema);
  const snapshot = await readFile(postgrestTypes, "utf8");
  const syntax = ts.createSourceFile(postgrestTypes, snapshot, ts.ScriptTarget.Latest, true);
  const database = syntax.statements.find((node) =>
    (ts.isTypeAliasDeclaration(node) || ts.isInterfaceDeclaration(node)) && node.name.text === "Database"
    && node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword));
  if (!database) throw new Error("PostgREST snapshot must export Database from the official type generator");
  const program = ts.createProgram([postgrestTypes], {
    strict: true, noEmit: true, skipLibCheck: true, types: [], target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler,
  });
  if (ts.getPreEmitDiagnostics(program).length) throw new Error("PostgREST snapshot has TypeScript errors");
  const artifacts = await renderGraphql({
    rootDir, outDir, graphql: options.graphql,
  });
  if (artifacts.diagnostics.some((item) => item.severity === "error")) {
    throw new Error(artifacts.diagnostics.map((item) => item.message).join("\n"));
  }
  const inputs: Record<string, string> = {};
  const addInput = async (path: string) => {
    const absolute = resolve(rootDir, path);
    inputs[relative(rootDir, absolute).replaceAll("\\", "/")] = hash(await readFile(absolute, "utf8"));
  };
  await addInput(postgrestTypes);
  await addInput(drizzleSchema);
  // Track local type imports too: a split Drizzle schema must invalidate the contract.
  const drizzleProgram = ts.createProgram([drizzleSchema], {
    noEmit: true, moduleResolution: ts.ModuleResolutionKind.Bundler, module: ts.ModuleKind.ESNext,
    target: ts.ScriptTarget.ES2022, types: [], skipLibCheck: true,
  });
  for (const source of drizzleProgram.getSourceFiles()) {
    if (!source.isDeclarationFile && !source.fileName.includes("/node_modules/")) await addInput(source.fileName);
  }
  await addInput(resolve(rootDir, options.graphql.schema));
  if (new Set(options.migrations.map((path) => resolve(rootDir, path))).size !== options.migrations.length) {
    throw new Error("Duplicate migration in database contracts configuration");
  }
  for (const path of options.migrations) await addInput(path);
  const files: Record<string, string> = {
    ...artifacts.files,
    "database.ts": [
      "// GENERATED BY @supacloud/compiler database-contracts. Do not edit.",
      `export type { Database } from ${JSON.stringify(importPath(outDir, postgrestTypes))};`,
      'export type { QueryData, QueryResult, QueryError } from "@supabase/supabase-js";',
      `export type DrizzleSchema = typeof import(${JSON.stringify(importPath(outDir, drizzleSchema))});`,
      'export * from "./graphql";',
      "",
    ].join("\n"),
  };
  const manifest = {
    version: 1, role: options.role,
    inputs: Object.fromEntries(Object.entries(inputs).sort(([a], [b]) => a.localeCompare(b))),
    migrationOrder: options.migrations.map((path) => relative(rootDir, resolve(rootDir, path)).replaceAll("\\", "/")),
    outputs: Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)).map(([file, text]) => [file, hash(text)])),
  };
  files["database.manifest.json"] = JSON.stringify(manifest, null, 2) + "\n";
  const mismatches: string[] = [];
  for (const [file, content] of Object.entries(files)) {
    const path = resolve(outDir, file);
    let current: string | undefined;
    try { current = await readFile(path, "utf8"); } catch (error) {
      if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
    }
    if (current !== content) mismatches.push(file);
  }
  if (!check) {
    await mkdir(outDir, { recursive: true });
    // Manifest is the completion marker and is written last.
    for (const [file, content] of Object.entries(files)) await writeFileIfChanged(resolve(outDir, file), content);
  }
  return { upToDate: mismatches.length === 0, mismatches, written: check ? [] : mismatches, manifest };
}

export async function runDatabaseContractsFile(path: string, check = false) {
  const absolute = resolve(path);
  const value: unknown = JSON.parse(await readFile(absolute, "utf8"));
  return generateDatabaseContracts(parseDatabaseContractsOptions(value, dirname(absolute)), check);
}
