import { mkdir, rename, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ApplicationGraph,
  ControllerNode,
  ModuleNode,
  ProviderNode,
  Scope,
} from "./types";
import {
  camelName,
  isJobContextToken,
  isRequestContextToken,
  joinRoutePaths,
  relativeImportPath,
} from "./util";

const HEADER = "// GENERATED BY @supacloud/compiler — do not edit";

const INTERFACES = `export interface CompiledRoute {
  method: string;
  path: string;
  handler: string;
  body?: unknown;
  params?: unknown;
  query?: unknown;
  response?: unknown;
  command?: string;
  guards?: string[];
  resolvers?: Record<string, string>;
  redirectTo?: string;
  pathMatch?: "full" | "prefix";
}

export interface CompiledCommand {
  className: string;
  name: string;
  permission: string;
  transaction: "required" | "none";
  audit?: string;
  idempotency: "required" | "none";
  standalone?: boolean;
}

export interface CompiledController {
  path: string;
  serviceKey: string;
  scope: string;
  routes: CompiledRoute[];
}

export interface CompiledModule {
  name: string;
  createServices(
    deps: Record<string, unknown>,
    imported: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  createRequestScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  createJobScope?(
    services: Record<string, unknown>,
    ctx: unknown,
    imported?: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  controllers: CompiledController[];
  commands: CompiledCommand[];
}`;

export interface GenerateOptions {
  rootDir: string;
  outDir: string;
  generateClient?: boolean;
  generatePermissions?: boolean;
}

export interface RenderedArtifacts {
  applicationCode: string;
  manifestJson: string;
  clientCode?: string;
  permissionsCode?: string;
}

/** Render application.ts and app.manifest.json content without file I/O. */
export function renderApplication(
  graph: ApplicationGraph,
  options: GenerateOptions,
): RenderedArtifacts {
  const modules = topoSortModules(graph.modules);
  const imports = new ImportManager();

  const factorySections: string[] = [];
  const descriptorEntries: string[] = [];
  for (const module of modules) {
    const gen = new ModuleGenerator(graph, module, imports);
    factorySections.push(...gen.renderFactories());
    descriptorEntries.push(gen.renderDescriptor());
  }

  const code = [
    HEADER,
    "",
    ...imports.render(options.rootDir, options.outDir),
    ...(imports.size > 0 ? [""] : []),
    INTERFACES,
    "",
    "export function createCompiledModules(): CompiledModule[] {",
    "  return [",
    ...descriptorEntries.map((entry) => indent(entry, 4) + ","),
    "  ];",
    "}",
    "",
    "export async function initializeApplication(services: Record<string, unknown>): Promise<void> {",
    '  const initializers = (services.appInitializer ?? (services as any)["supacloud.app-initializer"]) as unknown;',
    "  if (Array.isArray(initializers)) {",
    "    for (const init of initializers) {",
    '      if (typeof init === "function") await init();',
    "    }",
    '  } else if (typeof initializers === "function") {',
    "    await (initializers as () => unknown)();",
    "  }",
    "}",
    "",
    ...factorySections,
    "",
  ].join("\n");

  const manifest = {
    version: 1,
    modules: graph.modules,
    externalTokens: graph.externalTokens,
  };

  const clientCode = options.generateClient ? renderClient(graph, options) : undefined;
  const permissionsCode = options.generatePermissions ? renderPermissions(graph) : undefined;

  return {
    applicationCode: code,
    manifestJson: JSON.stringify(manifest, null, 2) + "\n",
    clientCode,
    permissionsCode,
  };
}

/**
 * Generate static factory code (application.ts) and app.manifest.json.
 * Generated code imports only application classes and schemas, with no runtime reflection or container lookup.
 */
export async function generateApplication(
  graph: ApplicationGraph,
  options: GenerateOptions,
): Promise<string[]> {
  const rendered = renderApplication(graph, options);

  await mkdir(options.outDir, { recursive: true });
  const applicationPath = join(options.outDir, "application.ts");
  const manifestPath = join(options.outDir, "app.manifest.json");
  await writeFileAtomic(applicationPath, rendered.applicationCode);
  await writeFileAtomic(manifestPath, rendered.manifestJson);

  const written = [applicationPath, manifestPath];
  if (rendered.clientCode) {
    const clientPath = join(options.outDir, "client.ts");
    await writeFileAtomic(clientPath, rendered.clientCode);
    written.push(clientPath);
  }
  if (rendered.permissionsCode) {
    const permissionsPath = join(options.outDir, "permissions.ts");
    await writeFileAtomic(permissionsPath, rendered.permissionsCode);
    written.push(permissionsPath);
  }
  return written;
}

async function writeFileAtomic(path: string, content: string): Promise<void> {
  const temporaryPath = `${path}.tmp-${process.pid}-${Math.random().toString(36).slice(2)}`;
  try {
    await writeFile(temporaryPath, content, "utf8");
    await rename(temporaryPath, path);
  } catch (error) {
    await unlink(temporaryPath).catch(() => undefined);
    throw error;
  }
}

type FactoryKind = "services" | "request" | "job";

function factoryOfScope(scope: Scope): FactoryKind {
  return scope === "application" ? "services" : scope;
}

/** Topologically sorts modules by imports (dependees first), preserving original relative ordering. */
function topoSortModules(modules: ModuleNode[]): ModuleNode[] {
  const byName = new Map(modules.map((m) => [m.name, m]));
  const visited = new Set<string>();
  const result: ModuleNode[] = [];
  const visit = (module: ModuleNode): void => {
    if (visited.has(module.name)) return;
    visited.add(module.name);
    for (const importName of module.imports) {
      const dep = byName.get(importName);
      if (dep && dep !== module) visit(dep);
    }
    result.push(module);
  };
  for (const module of modules) visit(module);
  return result;
}

function pascalName(name: string): string {
  const joined = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return joined || "App";
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

/** Manages generated file imports: automatically aliases symbols with the same name from different sources. */
class ImportManager {
  private readonly entries = new Map<string, { path: string; exported: string }>();

  get size(): number {
    return this.entries.size;
  }

  /** Registers a symbol and returns local identifier for generated code. importPath is relative to rootDir without extension. */
  add(exported: string, importPath?: string): string {
    if (!importPath) return exported;
    for (const [local, entry] of this.entries) {
      if (entry.path === importPath && entry.exported === exported) return local;
    }
    let local = exported;
    let counter = 2;
    while (this.entries.has(local)) {
      local = `${exported}${counter}`;
      counter += 1;
    }
    this.entries.set(local, { path: importPath, exported });
    return local;
  }

  render(rootDir: string, outDir: string): string[] {
    const byPath = new Map<string, { exported: string; local: string }[]>();
    for (const [local, entry] of this.entries) {
      const list = byPath.get(entry.path) ?? [];
      list.push({ exported: entry.exported, local });
      byPath.set(entry.path, list);
    }
    return [...byPath.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([path, symbols]) => {
        const spec = relativeImportPath(outDir, join(rootDir, `${path}.ts`));
        const names = symbols
          .sort((a, b) => a.exported.localeCompare(b.exported))
          .map((s) => (s.local === s.exported ? s.exported : `${s.exported} as ${s.local}`))
          .join(", ");
        return `import { ${names} } from "${spec}";`;
      });
  }
}

/** Factory functions and CompiledModule descriptor generation for a single module. */
class ModuleGenerator {
  private readonly pascal: string;
  /** Token -> local variable name within each factory. */
  private readonly locals: Record<FactoryKind, Map<string, string>> = {
    services: new Map(),
    request: new Map(),
    job: new Map(),
  };

  constructor(
    private readonly graph: ApplicationGraph,
    private readonly module: ModuleNode,
    private readonly imports: ImportManager,
  ) {
    this.pascal = pascalName(module.name);
  }

  renderFactories(): string[] {
    const sections: string[] = [this.renderServicesFactory()];
    if (this.hasFactoryContent("request")) {
      sections.push(this.renderScopeFactory("request"));
    }
    if (this.hasFactoryContent("job")) {
      sections.push(this.renderScopeFactory("job"));
    }
    return sections;
  }

  renderDescriptor(): string {
    const lines: string[] = [
      `{`,
      `  name: ${JSON.stringify(this.module.name)},`,
      `  createServices: create${this.pascal}Services,`,
    ];
    if (this.hasFactoryContent("request")) {
      lines.push(`  createRequestScope: create${this.pascal}RequestScope,`);
    }
    if (this.hasFactoryContent("job")) {
      lines.push(`  createJobScope: create${this.pascal}JobScope,`);
    }
    lines.push(`  controllers: ${this.renderControllers()},`);
    lines.push(`  commands: ${JSON.stringify(this.module.commands)},`);
    lines.push(`}`);
    return lines.join("\n");
  }

  private hasFactoryContent(kind: Exclude<FactoryKind, "services">): boolean {
    return (
      this.module.providers.some((p) => factoryOfScope(p.scope) === kind) ||
      this.module.controllers.some((c) => factoryOfScope(c.scope) === kind)
    );
  }

  private renderControllers(): string {
    if (this.module.controllers.length === 0) return "[]";
    const items = this.module.controllers.map((controller) => {
      const routes = controller.routes.map((route) => {
        const fields: string[] = [
          `method: ${JSON.stringify(route.method)}`,
          `path: ${JSON.stringify(route.path)}`,
          `handler: ${JSON.stringify(route.handler)}`,
        ];
        for (const field of ["body", "params", "query", "response"] as const) {
          const symbol = route[field];
          if (symbol) {
            const local = this.imports.add(symbol, controller.schemaImports?.[symbol]);
            fields.push(`${field}: ${local}`);
          }
        }
        if (route.command) fields.push(`command: ${JSON.stringify(route.command)}`);
        if (route.guards && route.guards.length > 0) {
          fields.push(`guards: ${JSON.stringify(route.guards)}`);
        }
        if (route.resolvers && Object.keys(route.resolvers).length > 0) {
          fields.push(`resolvers: ${JSON.stringify(route.resolvers)}`);
        }
        if (route.redirectTo) {
          fields.push(`redirectTo: ${JSON.stringify(route.redirectTo)}`);
        }
        if (route.pathMatch) {
          fields.push(`pathMatch: ${JSON.stringify(route.pathMatch)}`);
        }
        return `{ ${fields.join(", ")} }`;
      });
      return [
        `{`,
        `  path: ${JSON.stringify(controller.path)},`,
        `  serviceKey: ${JSON.stringify(camelName(controller.className))},`,
        `  scope: ${JSON.stringify(controller.scope)},`,
        `  routes: [${routes.join(", ")}],`,
        `}`,
      ].join("\n");
    });
    return `[${items.map((item) => `\n${indent(item, 2)}`).join(",")}\n]`;
  }

  private renderServicesFactory(): string {
    return [
      `function create${this.pascal}Services(`,
      `  deps: Record<string, unknown>,`,
      `  imported: Record<string, Record<string, unknown>>,`,
      `): Record<string, unknown> {`,
      indent(this.renderFactoryBody("services"), 2),
      `}`,
    ].join("\n");
  }

  private renderScopeFactory(kind: "request" | "job"): string {
    const suffix = kind === "request" ? "RequestScope" : "JobScope";
    return [
      `function create${this.pascal}${suffix}(`,
      `  services: Record<string, unknown>,`,
      `  ctx: unknown,`,
      `  imported: Record<string, Record<string, unknown>> = {},`,
      `): Record<string, unknown> {`,
      indent(this.renderFactoryBody(kind), 2),
      `}`,
    ].join("\n");
  }

  /** Factory function body: instantiates providers and controllers for this scope in dependency topological order. */
  private renderFactoryBody(kind: FactoryKind): string {
    const providers = orderProviders(
      this.module.providers.filter((p) => factoryOfScope(p.scope) === kind),
    );
    const controllers = this.module.controllers.filter(
      (c) => factoryOfScope(c.scope) === kind,
    );

    const lines: string[] = [];
    const returns = new Map<string, string>();
    const multiGroups = new Map<string, string[]>();

    for (const provider of providers) {
      if (provider.multi) {
        const emitted = this.emitProvider(provider, kind, true);
        if (emitted.constLine) lines.push(emitted.constLine);
        const list = multiGroups.get(emitted.key) ?? [];
        list.push(emitted.expr);
        multiGroups.set(emitted.key, list);
      } else {
        const emitted = this.emitProvider(provider, kind, false);
        if (emitted.constLine) lines.push(emitted.constLine);
        returns.set(emitted.key, emitted.expr);
      }
    }
    for (const [key, exprs] of multiGroups) {
      returns.set(key, `[${exprs.join(", ")}]`);
    }
    for (const controller of controllers) {
      const emitted = this.emitController(controller, kind);
      lines.push(emitted.constLine);
      returns.set(emitted.key, emitted.expr);
    }
    const entries = [...returns.entries()].map(([key, expr]) =>
      key === expr ? key : `${key}: ${expr}`,
    );
    lines.push(`return { ${entries.join(", ")} };`);
    return lines.join("\n");
  }

  private emitProvider(
    provider: ProviderNode,
    kind: FactoryKind,
    isMulti = false,
  ): { constLine?: string; key: string; expr: string } {
    const key = camelName(provider.token);
    switch (provider.kind) {
      case "class": {
        const useClass = this.imports.add(provider.useClass ?? provider.token, provider.importPath);
        const args = provider.deps
          .map((dep) => this.depExpr(dep, kind, provider.optionalDeps?.includes(dep)))
          .join(", ");
        const local = this.localVar(isMulti ? (provider.useClass ?? `${provider.token}Item`) : provider.token, kind);
        return { constLine: `const ${local} = new ${useClass}(${args});`, key, expr: local };
      }
      case "value": {
        const expr = provider.importPath
          ? this.imports.add(provider.useValueExpr ?? "undefined", provider.importPath)
          : (provider.useValueExpr ?? "undefined");
        const local = this.localVar(isMulti ? `${provider.token}Item` : provider.token, kind);
        return { constLine: `const ${local} = ${expr};`, key, expr: local };
      }
      case "factory": {
        const factory = this.imports.add(provider.useFactoryName ?? "", provider.importPath);
        const args = provider.deps
          .map((dep) => this.depExpr(dep, kind, provider.optionalDeps?.includes(dep)))
          .join(", ");
        const local = this.localVar(isMulti ? (provider.useFactoryName ?? `${provider.token}Item`) : provider.token, kind);
        return { constLine: `const ${local} = ${factory}(${args});`, key, expr: local };
      }
      case "existing": {
        // Alias provider: does not create a new instance, directly references target expression.
        return { key, expr: this.depExpr(provider.useExisting ?? provider.token, kind, provider.optionalDeps?.includes(provider.token)) };
      }
    }
  }

  private emitController(
    controller: ControllerNode,
    kind: FactoryKind,
  ): { constLine: string; key: string; expr: string } {
    const className = this.imports.add(controller.className, controller.importPath);
    const args = controller.deps
      .map((dep) => this.depExpr(dep, kind, controller.optionalDeps?.includes(dep)))
      .join(", ");
    const key = camelName(controller.className);
    const local = this.localVar(controller.className, kind);
    return { constLine: `const ${local} = new ${className}(${args});`, key, expr: local };
  }

  /** Token -> local variable name in factory (camelCase, suffixed with digits on conflict). */
  private localVar(token: string, kind: FactoryKind): string {
    const locals = this.locals[kind];
    const existing = locals.get(token);
    if (existing) return existing;
    const base = camelName(token);
    let local = base;
    let counter = 2;
    while ([...locals.values()].includes(local)) {
      local = `${base}${counter}`;
      counter += 1;
    }
    locals.set(token, local);
    return local;
  }

  /**
   * Dependency resolution order:
   * Provider instantiated in current factory > Module application services (services.<key>) >
   * Services exported by imported modules (imported.<module>.<key>, accessed via services param in
   * request/job factories) > Platform deps (deps.<camelName>).
   */
  private depExpr(token: string, kind: FactoryKind, isOptional = false): string {
    if (kind === "request" && isRequestContextToken(token, this.graph.tokenNames)) return "ctx";
    if (kind === "job" && isJobContextToken(token, this.graph.tokenNames)) return "ctx";

    const own = this.module.providers.find((p) => p.token === token);
    if (own) {
      if (factoryOfScope(own.scope) === kind && own.kind !== "existing") {
        return this.locals[kind].get(token) ?? camelName(token);
      }
      if (own.kind === "existing" && factoryOfScope(own.scope) === kind) {
        return this.depExpr(own.useExisting ?? token, kind, isOptional);
      }
      if (kind === "services") {
        // Application factory referencing request/job provider: scope-violation, already flagged by validator.
        return `services.${camelName(token)}`;
      }
      return `services.${camelName(token)}`;
    }

    for (const importName of this.module.imports) {
      const imported = this.graph.modules.find((m) => m.name === importName);
      if (!imported?.exports.includes(token)) continue;
      if (kind === "services") return `imported.${importName}.${camelName(token)}`;
      return `imported.${importName}.${camelName(token)}`;
    }

    for (const mod of this.graph.modules) {
      const rootProv = mod.providers.find((p) => p.token === token && p.providedIn === "root");
      if (rootProv) {
        return `imported.${mod.name}.${camelName(token)}`;
      }
    }

    if (isOptional && !this.graph.externalTokens.includes(token)) {
      return "undefined";
    }

    if (kind === "services") return isOptional ? `(deps.${camelName(token)} ?? undefined)` : `deps.${camelName(token)}`;
    // request/job factories have no deps parameter; platform/external tokens are also passed via services.
    return isOptional ? `(services.${camelName(token)} ?? undefined)` : `services.${camelName(token)}`;
  }
}

/** Stable topological sort of providers within a factory: providers depending on peers in the same factory are placed after them. */
function orderProviders(providers: ProviderNode[]): ProviderNode[] {
  const remaining = [...providers];
  const emitted = new Set<string>();
  const result: ProviderNode[] = [];
  while (remaining.length > 0) {
    const index = remaining.findIndex((p) =>
      p.deps.every((dep) => {
        const depProvider = providers.find((x) => x.token === dep);
        return !depProvider || emitted.has(dep);
      }),
    );
    if (index === -1) {
      // Circular dependency: output in original order (validateGraph already reported circular-dependency).
      result.push(...remaining.splice(0));
      break;
    }
    const [provider] = remaining.splice(index, 1);
  emitted.add(provider.token);
  result.push(provider);
}
return result;
}

/**
 * Generates typed API client in client.ts from discovered Controllers and Routes.
 * Modeled after Angular HttpClient and typed contract clients.
 */
export function renderClient(graph: ApplicationGraph, _options?: GenerateOptions): string {
  const controllerEntries: string[] = [];
  const allRoutes: Array<{
    method: string;
    path: string;
    controller: string;
    handler: string;
    command?: string;
    guards?: string[];
    resolvers?: Record<string, string>;
    redirectTo?: string;
    pathMatch?: "full" | "prefix";
  }> = [];

  for (const module of graph.modules) {
    for (const controller of module.controllers) {
      const controllerKey = camelName(controller.className.replace(/Controller$/, ""));
      const routeMethods: string[] = [];

      for (const route of controller.routes) {
        const fullPath = joinRoutePaths(controller.path, route.path);
        allRoutes.push({
          method: route.method,
          path: fullPath,
          controller: controller.className,
          handler: route.handler,
          command: route.command,
          guards: route.guards,
          resolvers: route.resolvers,
          redirectTo: route.redirectTo,
          pathMatch: route.pathMatch,
        });

        routeMethods.push(`
    ${route.handler}: (options: {
      params?: Record<string, string | number>;
      query?: Record<string, unknown>;
      body?: unknown;
      headers?: Record<string, string>;
    } = {}) => request(${JSON.stringify(route.method)}, ${JSON.stringify(fullPath)}, options),`);
      }

      controllerEntries.push(`
  ${controllerKey}: {${routeMethods.join("")}
  },`);
    }
  }

  return [
    HEADER,
    "",
    "export interface ClientRequestOptions {",
    "  params?: Record<string, string | number>;",
    "  query?: Record<string, unknown>;",
    "  body?: unknown;",
    "  headers?: Record<string, string>;",
    "}",
    "",
    "export type HttpInterceptorFn = (",
    "  req: { method: string; url: string; headers: Record<string, string>; body?: unknown },",
    "  next: (req: { method: string; url: string; headers: Record<string, string>; body?: unknown }) => Promise<Response>,",
    ") => Promise<Response>;",
    "",
    "export interface ApiClientConfig {",
    "  baseUrl?: string;",
    "  fetch?: typeof fetch;",
    "  headers?: Record<string, string> | (() => Record<string, string> | Promise<Record<string, string>>);",
    "  interceptors?: HttpInterceptorFn[];",
    "}",
    "",
    "export const API_ROUTES = " + JSON.stringify(allRoutes, null, 2) + " as const;",
    "",
    "export function createApiClient(config: ApiClientConfig = {}) {",
    "  const fetcher = config.fetch ?? globalThis.fetch.bind(globalThis);",
    '  const baseUrl = (config.baseUrl ?? "").replace(/\\/+$/, "");',
    "",
    "  async function request<T = unknown>(",
    "    method: string,",
    "    path: string,",
    "    options: ClientRequestOptions = {},",
    "  ): Promise<T> {",
    "    let url = `${baseUrl}${path}`;",
    "    if (options.params) {",
    "      for (const [key, value] of Object.entries(options.params)) {",
    "        url = url.replace(`:${key}`, encodeURIComponent(String(value)));",
    "      }",
    "    }",
    "    if (options.query) {",
    "      const searchParams = new URLSearchParams();",
    "      for (const [k, v] of Object.entries(options.query)) {",
    "        if (v !== undefined && v !== null) searchParams.set(k, String(v));",
    "      }",
    "      const qs = searchParams.toString();",
    '      if (qs) url += (url.includes("?") ? "&" : "?") + qs;',
    "    }",
    '    const customHeaders = typeof config.headers === "function" ? await config.headers() : config.headers;',
    "    const headers: Record<string, string> = {",
    '      "content-type": "application/json",',
    "      ...customHeaders,",
    "      ...options.headers,",
    "    };",
    "    const interceptors = config.interceptors ?? [];",
    "    const executeChain = (",
    "      index: number,",
    "      reqPayload: { method: string; url: string; headers: Record<string, string>; body?: unknown },",
    "    ): Promise<Response> => {",
    "      if (index < interceptors.length) {",
    "        return interceptors[index](reqPayload, (nextPayload) => executeChain(index + 1, nextPayload));",
    "      }",
    "      return fetcher(reqPayload.url, {",
    "        method: reqPayload.method,",
    "        headers: reqPayload.headers,",
    "        body: reqPayload.body !== undefined ? JSON.stringify(reqPayload.body) : undefined,",
    "      });",
    "    };",
    "    const response = await executeChain(0, { method, url, headers, body: options.body });",
    "    if (!response.ok) {",
    "      const errBody = await response.text();",
    "      throw new Error(`API request failed: ${method} ${path} -> ${response.status} ${errBody}`);",
    "    }",
    '    const contentType = response.headers?.get("content-type") ?? "";',
    '    if (contentType.includes("application/json")) {',
    "      return response.json() as Promise<T>;",
    "    }",
    "    return response.text() as Promise<T>;",
    "  }",
    "",
    "  return {",
    "    request,",
    ...controllerEntries,
    "  };",
    "}",
    "",
    "export type ApiClient = ReturnType<typeof createApiClient>;",
    "",
  ].join("\n");
}

/**
 * Generates static permissions and route permission bindings in permissions.ts.
 */
export function renderPermissions(graph: ApplicationGraph): string {
  const permissions = new Set<string>();
  const bindings: Array<{
    method: string;
    path: string;
    controller: string;
    handler: string;
    command?: string;
    permission?: string;
  }> = [];

  for (const module of graph.modules) {
    for (const command of module.commands) {
      if (command.permission) permissions.add(command.permission);
    }
    for (const controller of module.controllers) {
      for (const route of controller.routes) {
        let perm: string | undefined;
        if (route.command) {
          const cmd = module.commands.find((c) => c.className === route.command);
          perm = cmd?.permission;
        }
        if (perm) permissions.add(perm);
        bindings.push({
          method: route.method,
          path: joinRoutePaths(controller.path, route.path),
          controller: controller.className,
          handler: route.handler,
          command: route.command,
          permission: perm,
        });
      }
    }
  }

  const sortedPerms = [...permissions].sort();
  const enumEntries = sortedPerms.map((perm) => {
    const key = pascalName(perm.replace(/[^A-Za-z0-9]+/g, " "));
    return `  ${key}: ${JSON.stringify(perm)},`;
  });

  return [
    HEADER,
    "",
    "export const AppPermissions = {",
    ...enumEntries,
    "} as const;",
    "",
    "export type AppPermission = (typeof AppPermissions)[keyof typeof AppPermissions];",
    "",
    "export interface RoutePermissionBinding {",
    "  method: string;",
    "  path: string;",
    "  controller: string;",
    "  handler: string;",
    "  command?: string;",
    "  permission?: string;",
    "}",
    "",
    "export const RoutePermissions: RoutePermissionBinding[] = " + JSON.stringify(bindings, null, 2) + ";",
    "",
    "export function hasPermission(granted: string[], required: AppPermission | string): boolean {",
    '  return granted.includes("*") || granted.includes(required);',
    "}",
    "",
  ].join("\n");
}
