import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ApplicationGraph,
  ControllerNode,
  ModuleNode,
  ProviderNode,
  Scope,
} from "./types";
import {
  camelName,
  isJobContextToken,
  isRequestContextToken,
  relativeImportPath,
} from "./util";

const HEADER = "// GENERATED BY @supacloud/compiler — do not edit";

const INTERFACES = `export interface CompiledRoute {
  method: string;
  path: string;
  handler: string;
  body?: unknown;
  params?: unknown;
  query?: unknown;
  response?: unknown;
}

export interface CompiledController {
  path: string;
  serviceKey: string;
  scope: string;
  routes: CompiledRoute[];
}

export interface CompiledModule {
  name: string;
  createServices(
    deps: Record<string, unknown>,
    imported: Record<string, Record<string, unknown>>,
  ): Record<string, unknown>;
  createRequestScope?(
    services: Record<string, unknown>,
    ctx: unknown,
  ): Record<string, unknown>;
  createJobScope?(
    services: Record<string, unknown>,
    ctx: unknown,
  ): Record<string, unknown>;
  controllers: CompiledController[];
}`;

export interface GenerateOptions {
  rootDir: string;
  outDir: string;
}

/**
 * 生成静态工厂代码（application.ts）与 app.manifest.json，返回写入的绝对路径。
 * 生成代码只 import 业务类/schema，不 import @supacloud/app，运行期无反射、无容器。
 */
export async function generateApplication(
  graph: ApplicationGraph,
  options: GenerateOptions,
): Promise<string[]> {
  const modules = topoSortModules(graph.modules);
  const imports = new ImportManager();

  const factorySections: string[] = [];
  const descriptorEntries: string[] = [];
  for (const module of modules) {
    const gen = new ModuleGenerator(graph, module, imports);
    factorySections.push(...gen.renderFactories());
    descriptorEntries.push(gen.renderDescriptor());
  }

  const code = [
    HEADER,
    "",
    ...imports.render(options.rootDir, options.outDir),
    ...(imports.size > 0 ? [""] : []),
    INTERFACES,
    "",
    "export function createCompiledModules(deps: Record<string, unknown>): CompiledModule[] {",
    "  return [",
    ...descriptorEntries.map((entry) => indent(entry, 4) + ","),
    "  ];",
    "}",
    "",
    ...factorySections,
    "",
  ].join("\n");

  const manifest = {
    version: 1,
    modules: graph.modules,
    externalTokens: graph.externalTokens,
  };

  await mkdir(options.outDir, { recursive: true });
  const applicationPath = join(options.outDir, "application.ts");
  const manifestPath = join(options.outDir, "app.manifest.json");
  await writeFile(applicationPath, code, "utf8");
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  return [applicationPath, manifestPath];
}

type FactoryKind = "services" | "request" | "job";

function factoryOfScope(scope: Scope): FactoryKind {
  return scope === "application" ? "services" : scope;
}

/** 按 imports 拓扑排序模块（被依赖者在前），保持原有相对顺序。 */
function topoSortModules(modules: ModuleNode[]): ModuleNode[] {
  const byName = new Map(modules.map((m) => [m.name, m]));
  const visited = new Set<string>();
  const result: ModuleNode[] = [];
  const visit = (module: ModuleNode): void => {
    if (visited.has(module.name)) return;
    visited.add(module.name);
    for (const importName of module.imports) {
      const dep = byName.get(importName);
      if (dep && dep !== module) visit(dep);
    }
    result.push(module);
  };
  for (const module of modules) visit(module);
  return result;
}

function pascalName(name: string): string {
  const joined = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return joined || "App";
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? pad + line : line))
    .join("\n");
}

/** 管理生成文件的 import：同名不同源符号自动取别名。 */
class ImportManager {
  private readonly entries = new Map<string, { path: string; exported: string }>();

  get size(): number {
    return this.entries.size;
  }

  /** 注册符号，返回生成代码中可用的本地名。importPath 为 rootDir 相对、无扩展名。 */
  add(exported: string, importPath?: string): string {
    if (!importPath) return exported;
    for (const [local, entry] of this.entries) {
      if (entry.path === importPath && entry.exported === exported) return local;
    }
    let local = exported;
    let counter = 2;
    while (this.entries.has(local)) {
      local = `${exported}${counter}`;
      counter += 1;
    }
    this.entries.set(local, { path: importPath, exported });
    return local;
  }

  render(rootDir: string, outDir: string): string[] {
    const byPath = new Map<string, { exported: string; local: string }[]>();
    for (const [local, entry] of this.entries) {
      const list = byPath.get(entry.path) ?? [];
      list.push({ exported: entry.exported, local });
      byPath.set(entry.path, list);
    }
    return [...byPath.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([path, symbols]) => {
        const spec = relativeImportPath(outDir, join(rootDir, `${path}.ts`));
        const names = symbols
          .sort((a, b) => a.exported.localeCompare(b.exported))
          .map((s) => (s.local === s.exported ? s.exported : `${s.exported} as ${s.local}`))
          .join(", ");
        return `import { ${names} } from "${spec}";`;
      });
  }
}

/** 单个模块的工厂函数 + CompiledModule 描述对象生成。 */
class ModuleGenerator {
  private readonly pascal: string;
  /** 每个工厂内 token → 局部变量名。 */
  private readonly locals: Record<FactoryKind, Map<string, string>> = {
    services: new Map(),
    request: new Map(),
    job: new Map(),
  };

  constructor(
    private readonly graph: ApplicationGraph,
    private readonly module: ModuleNode,
    private readonly imports: ImportManager,
  ) {
    this.pascal = pascalName(module.name);
  }

  renderFactories(): string[] {
    const sections: string[] = [this.renderServicesFactory()];
    if (this.hasFactoryContent("request")) {
      sections.push(this.renderScopeFactory("request"));
    }
    if (this.hasFactoryContent("job")) {
      sections.push(this.renderScopeFactory("job"));
    }
    return sections;
  }

  renderDescriptor(): string {
    const lines: string[] = [
      `{`,
      `  name: ${JSON.stringify(this.module.name)},`,
      `  createServices: create${this.pascal}Services,`,
    ];
    if (this.hasFactoryContent("request")) {
      lines.push(`  createRequestScope: create${this.pascal}RequestScope,`);
    }
    if (this.hasFactoryContent("job")) {
      lines.push(`  createJobScope: create${this.pascal}JobScope,`);
    }
    lines.push(`  controllers: ${this.renderControllers()},`);
    lines.push(`}`);
    return lines.join("\n");
  }

  private hasFactoryContent(kind: Exclude<FactoryKind, "services">): boolean {
    return (
      this.module.providers.some((p) => factoryOfScope(p.scope) === kind) ||
      this.module.controllers.some((c) => factoryOfScope(c.scope) === kind)
    );
  }

  private renderControllers(): string {
    if (this.module.controllers.length === 0) return "[]";
    const items = this.module.controllers.map((controller) => {
      const routes = controller.routes.map((route) => {
        const fields: string[] = [
          `method: ${JSON.stringify(route.method)}`,
          `path: ${JSON.stringify(route.path)}`,
          `handler: ${JSON.stringify(route.handler)}`,
        ];
        for (const field of ["body", "params", "query", "response"] as const) {
          const symbol = route[field];
          if (symbol) {
            const local = this.imports.add(symbol, controller.schemaImports?.[symbol]);
            fields.push(`${field}: ${local}`);
          }
        }
        return `{ ${fields.join(", ")} }`;
      });
      return [
        `{`,
        `  path: ${JSON.stringify(controller.path)},`,
        `  serviceKey: ${JSON.stringify(camelName(controller.className))},`,
        `  scope: ${JSON.stringify(controller.scope)},`,
        `  routes: [${routes.join(", ")}],`,
        `}`,
      ].join("\n");
    });
    return `[${items.map((item) => `\n${indent(item, 2)}`).join(",")}\n]`;
  }

  private renderServicesFactory(): string {
    return [
      `function create${this.pascal}Services(`,
      `  deps: Record<string, unknown>,`,
      `  imported: Record<string, Record<string, unknown>>,`,
      `): Record<string, unknown> {`,
      indent(this.renderFactoryBody("services"), 2),
      `}`,
    ].join("\n");
  }

  private renderScopeFactory(kind: "request" | "job"): string {
    const suffix = kind === "request" ? "RequestScope" : "JobScope";
    return [
      `function create${this.pascal}${suffix}(`,
      `  services: Record<string, unknown>,`,
      `  ctx: unknown,`,
      `): Record<string, unknown> {`,
      indent(this.renderFactoryBody(kind), 2),
      `}`,
    ].join("\n");
  }

  /** 工厂函数体：按依赖拓扑序实例化该 scope 的 provider 与 controller。 */
  private renderFactoryBody(kind: FactoryKind): string {
    const providers = orderProviders(
      this.module.providers.filter((p) => factoryOfScope(p.scope) === kind),
    );
    const controllers = this.module.controllers.filter(
      (c) => factoryOfScope(c.scope) === kind,
    );

    const lines: string[] = [];
    const returns = new Map<string, string>();
    for (const provider of providers) {
      const emitted = this.emitProvider(provider, kind);
      if (emitted.constLine) lines.push(emitted.constLine);
      returns.set(emitted.key, emitted.expr);
    }
    for (const controller of controllers) {
      const emitted = this.emitController(controller, kind);
      lines.push(emitted.constLine);
      returns.set(emitted.key, emitted.expr);
    }
    const entries = [...returns.entries()].map(([key, expr]) =>
      key === expr ? key : `${key}: ${expr}`,
    );
    lines.push(`return { ${entries.join(", ")} };`);
    return lines.join("\n");
  }

  private emitProvider(
    provider: ProviderNode,
    kind: FactoryKind,
  ): { constLine?: string; key: string; expr: string } {
    const key = camelName(provider.token);
    switch (provider.kind) {
      case "class": {
        const useClass = this.imports.add(provider.useClass ?? provider.token, provider.importPath);
        const args = provider.deps.map((dep) => this.depExpr(dep, kind)).join(", ");
        const local = this.localVar(provider.token, kind);
        return { constLine: `const ${local} = new ${useClass}(${args});`, key, expr: local };
      }
      case "value": {
        const expr = provider.importPath
          ? this.imports.add(provider.useValueExpr ?? "undefined", provider.importPath)
          : (provider.useValueExpr ?? "undefined");
        const local = this.localVar(provider.token, kind);
        return { constLine: `const ${local} = ${expr};`, key, expr: local };
      }
      case "factory": {
        const factory = this.imports.add(provider.useFactoryName ?? "", provider.importPath);
        const args = provider.deps.map((dep) => this.depExpr(dep, kind)).join(", ");
        const local = this.localVar(provider.token, kind);
        return { constLine: `const ${local} = ${factory}(${args});`, key, expr: local };
      }
      case "existing": {
        // 别名 provider：不产生新实例，直接引用目标表达式。
        return { key, expr: this.depExpr(provider.useExisting ?? provider.token, kind) };
      }
    }
  }

  private emitController(
    controller: ControllerNode,
    kind: FactoryKind,
  ): { constLine: string; key: string; expr: string } {
    const className = this.imports.add(controller.className, controller.importPath);
    const args = controller.deps.map((dep) => this.depExpr(dep, kind)).join(", ");
    const key = camelName(controller.className);
    const local = this.localVar(controller.className, kind);
    return { constLine: `const ${local} = new ${className}(${args});`, key, expr: local };
  }

  /** token → 工厂内局部变量名（camelCase，冲突时加数字后缀）。 */
  private localVar(token: string, kind: FactoryKind): string {
    const locals = this.locals[kind];
    const existing = locals.get(token);
    if (existing) return existing;
    const base = camelName(token);
    let local = base;
    let counter = 2;
    while ([...locals.values()].includes(local)) {
      local = `${base}${counter}`;
      counter += 1;
    }
    locals.set(token, local);
    return local;
  }

  /**
   * dep 解析顺序：
   * 本工厂已实例化的 provider > 本模块 application services（services.<key>）>
   * imports 模块导出的 services（imported.<module>.<key>，request/job 工厂内经
   * services 参数访问）> 平台 deps（deps.<camelName>）。
   */
  private depExpr(token: string, kind: FactoryKind): string {
    if (kind === "request" && isRequestContextToken(token, this.graph.tokenNames)) return "ctx";
    if (kind === "job" && isJobContextToken(token, this.graph.tokenNames)) return "ctx";

    const own = this.module.providers.find((p) => p.token === token);
    if (own) {
      if (factoryOfScope(own.scope) === kind && own.kind !== "existing") {
        return this.locals[kind].get(token) ?? camelName(token);
      }
      if (own.kind === "existing" && factoryOfScope(own.scope) === kind) {
        return this.depExpr(own.useExisting ?? token, kind);
      }
      if (kind === "services") {
        // application 工厂引用 request/job provider：scope-violation，校验已报错。
        return `services.${camelName(token)}`;
      }
      return `services.${camelName(token)}`;
    }

    for (const importName of this.module.imports) {
      const imported = this.graph.modules.find((m) => m.name === importName);
      if (!imported?.exports.includes(token)) continue;
      if (kind === "services") return `imported.${importName}.${camelName(token)}`;
      return `services.${camelName(token)}`;
    }

    if (kind === "services") return `deps.${camelName(token)}`;
    // request/job 工厂无 deps 参数，平台/外部 token 也经 services 传入。
    return `services.${camelName(token)}`;
  }
}

/** 工厂内 provider 稳定拓扑排序：依赖同工厂 provider 的排后面。 */
function orderProviders(providers: ProviderNode[]): ProviderNode[] {
  const remaining = [...providers];
  const emitted = new Set<string>();
  const result: ProviderNode[] = [];
  while (remaining.length > 0) {
    const index = remaining.findIndex((p) =>
      p.deps.every((dep) => {
        const depProvider = providers.find((x) => x.token === dep);
        return !depProvider || emitted.has(dep);
      }),
    );
    if (index === -1) {
      // 循环依赖：保持原序输出（validateGraph 已报 circular-dependency）。
      result.push(...remaining.splice(0));
      break;
    }
    const [provider] = remaining.splice(index, 1);
    emitted.add(provider.token);
    result.push(provider);
  }
  return result;
}
