import { beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { checkProject, compileProject } from "./compile";
import { renderApplication } from "./generate";
import { BAD_PROJECT_FILES } from "./fixtures/bad-project";
import { GOOD_PROJECT_FILES } from "./fixtures/good-project";
import { writeFixtureProject } from "./fixtures/helpers";
import type { CompileResult } from "./types";

let rootDir: string;
let outDir: string;
let result: CompileResult;
let applicationCode: string;

beforeAll(async () => {
  rootDir = await mkdtemp(join(tmpdir(), "supacloud-compiler-gen-"));
  await writeFixtureProject(rootDir, GOOD_PROJECT_FILES);
  outDir = join(rootDir, "generated");
  result = await compileProject({ rootDir, outDir });
  applicationCode = await readFile(join(outDir, "application.ts"), "utf8");
}, 30_000);

describe("compileProject：总体结果", () => {
  test("无诊断，写出 application.ts 与 app.manifest.json", () => {
    expect(result.diagnostics).toEqual([]);
    expect(result.written).toEqual([
      join(outDir, "application.ts"),
      join(outDir, "app.manifest.json"),
    ]);
  });

  test("app.manifest.json 是 graph 的 JSON 序列化", async () => {
    const manifest = JSON.parse(
      await readFile(join(outDir, "app.manifest.json"), "utf8"),
    );
    expect(manifest.version).toBe(1);
    expect(manifest.externalTokens).toEqual(["DB_CLIENT", "REQUEST_CONTEXT"]);
    expect(manifest.modules.map((m: { name: string }) => m.name).sort()).toEqual([
      "audit",
      "case",
      "health",
    ]);
  });
});

describe("generate：application.ts 关键内容", () => {
  test("头注释与本地接口定义（不 import 外部包）", () => {
    expect(applicationCode).toStartWith(
      "// GENERATED BY @supacloud/compiler — do not edit",
    );
    expect(applicationCode).toContain("export interface CompiledModule {");
    expect(applicationCode).toContain("export interface CompiledController {");
    expect(applicationCode).toContain("export interface CompiledRoute {");
    expect(applicationCode).toContain("export interface CompiledCommand {");
    expect(applicationCode).not.toContain("@supacloud/app");
    expect(applicationCode).not.toContain("@supacloud/elysia");
  });

  test("业务类与 schema 以相对路径 import", () => {
    expect(applicationCode).toContain(
      'import { AuditService } from "../src/features/audit/audit.service";',
    );
    expect(applicationCode).toContain(
      'import { createLogger } from "../src/features/audit/logger";',
    );
    expect(applicationCode).toContain(
      'import { DrizzleCaseRepository } from "../src/features/case/case.repository";',
    );
    expect(applicationCode).toContain(
      'import { AcceptParams, AcceptResult, CreateCaseBody } from "../src/features/case/contracts";',
    );
  });

  test("模块按 imports 拓扑序出现在 createCompiledModules", () => {
    const auditIndex = applicationCode.indexOf('name: "audit"');
    const caseIndex = applicationCode.indexOf('name: "case"');
    const healthIndex = applicationCode.indexOf('name: "health"');
    expect(auditIndex).toBeGreaterThan(-1);
    expect(auditIndex).toBeLessThan(caseIndex);
    expect(caseIndex).toBeLessThan(healthIndex);
  });

  test("application 工厂：value/factory/class/existing 实例化与依赖解析", () => {
    expect(applicationCode).toContain('const auditConfig = { level: "info" };');
    expect(applicationCode).toContain("const logger = createLogger(auditConfig);");
    expect(applicationCode).toContain(
      "const auditService = new AuditService(auditConfig, logger);",
    );
    expect(applicationCode).toContain(
      "const caseRepository = new DrizzleCaseRepository(deps.dbClient);",
    );
    expect(applicationCode).toContain(
      "const caseService = new CaseService(caseRepository, imported.audit.auditService);",
    );
    expect(applicationCode).toContain(
      "const acceptCaseCommand = new AcceptCaseCommand(caseService);",
    );
  });

  test("request 工厂：REQUEST_CONTEXT 传 ctx，其余从 services 解析", () => {
    expect(applicationCode).toContain("createCaseRequestScope");
    expect(applicationCode).toContain(
      "const caseController = new CaseController(services.caseRepository, imported.audit.auditService, ctx);",
    );
  });

  test("controller 描述静态给出，schema 直接引用导入对象", () => {
    expect(applicationCode).toContain('serviceKey: "caseController"');
    expect(applicationCode).toContain('path: "/cases"');
    expect(applicationCode).toContain(
      '{ method: "POST", path: "/:caseId/accept", handler: "accept", body: CreateCaseBody, params: AcceptParams, response: AcceptResult, command: "AcceptCaseCommand" }',
    );
  });
});

describe("generate：application.ts 可被 bun 直接执行", () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let compiled: any;

  beforeAll(async () => {
    const url = pathToFileURL(join(outDir, "application.ts")).href;
    compiled = await import(url);
  });

  test("createCompiledModules 返回拓扑序模块描述", () => {
    const modules = compiled.createCompiledModules();
    expect(modules.map((m: { name: string }) => m.name)).toEqual([
      "audit",
      "case",
      "health",
    ]);
    expect(modules[0].controllers).toEqual([]);
    expect(modules[1].commands[0]).toMatchObject({
      className: "AcceptCaseCommand",
      name: "case.accept",
      permission: "case.accept",
    });
    expect(typeof modules[1].createRequestScope).toBe("function");
    expect(modules[2].createRequestScope).toBeUndefined();
  });

  test("services 实例化与跨模块依赖注入", () => {
    const modules = compiled.createCompiledModules();
    const deps = { dbClient: { kind: "fake-db" } };

    const auditServices = modules[0].createServices(deps, {});
    expect(auditServices.auditConfig).toEqual({ level: "info" });
    expect(auditServices.logger).toEqual({ level: "info" });
    expect(auditServices.auditService.config).toEqual({ level: "info" });
    expect(auditServices.auditService.logger).toBe(auditServices.logger);

    const caseServices = modules[1].createServices(deps, { audit: auditServices });
    expect(caseServices.caseRepository.db).toBe(deps.dbClient);
    expect(caseServices.caseService.repository).toBe(caseServices.caseRepository);
    expect(caseServices.caseService.audit).toBe(auditServices.auditService);
    expect(caseServices.acceptCaseCommand.caseService).toBe(caseServices.caseService);

    const healthServices = modules[2].createServices(deps, {});
    expect(healthServices.healthService.status()).toBe("ok");
  });

  test("request scope：ctx 注入且两次调用相互隔离", () => {
    const modules = compiled.createCompiledModules();
    const deps = { dbClient: {} };
    const caseModule = modules[1];
    const services = caseModule.createServices(deps, {
      audit: modules[0].createServices(deps, {}),
    });

    const ctx1 = { requestId: "r1" };
    const ctx2 = { requestId: "r2" };
    const imported = { audit: modules[0].createServices(deps, {}) };
    const scope1 = caseModule.createRequestScope(services, ctx1, imported);
    const scope2 = caseModule.createRequestScope(services, ctx2, imported);

    expect(scope1.caseController.ctx).toBe(ctx1);
    expect(scope1.caseController.repository).toBe(services.caseRepository);
    expect(scope1.caseController.audit).toBe(imported.audit.auditService);
    expect(scope2.caseController.ctx).toBe(ctx2);
    expect(scope2.caseController).not.toBe(scope1.caseController);
  });

  test("controller 路由 schema 引用与 contracts 模块导出的对象同一", async () => {
    const contracts = await import(
      pathToFileURL(join(rootDir, "src/features/case/contracts.ts")).href
    );
    const modules = compiled.createCompiledModules();
    const controller = modules[1].controllers[0];
    expect(controller.path).toBe("/cases");
    expect(controller.serviceKey).toBe("caseController");
    expect(controller.scope).toBe("request");
    expect(controller.routes).toHaveLength(1);
    expect(controller.routes[0].body).toBe(contracts.CreateCaseBody);
    expect(controller.routes[0].params).toBe(contracts.AcceptParams);
    expect(controller.routes[0].response).toBe(contracts.AcceptResult);
  });

  test("checkProject reports matching artifacts and detects drift", async () => {
    // 1. Freshly generated artifacts match.
    const check1 = await checkProject({ rootDir, outDir });
    expect(check1.upToDate).toBe(true);
    expect(check1.mismatches).toHaveLength(0);

    // 2. Tampering with a file must be detected.
    const manifestPath = join(outDir, "app.manifest.json");
    const originalContent = await readFile(manifestPath, "utf8");
    await writeFile(manifestPath, '{"tampered": true}\n', "utf8");

    try {
      const check2 = await checkProject({ rootDir, outDir });
      expect(check2.upToDate).toBe(false);
      expect(check2.mismatches.some((m) => m.includes("app.manifest.json"))).toBe(true);
    } finally {
      await writeFile(manifestPath, originalContent, "utf8");
    }
  });

  test("writeOnError=false 保留既有生成物，不写入错误版本", async () => {
    const badRoot = await mkdtemp(join(tmpdir(), "supacloud-compiler-error-"));
    const badOut = join(badRoot, "generated");
    await writeFixtureProject(badRoot, GOOD_PROJECT_FILES);
    const first = await compileProject({ rootDir: badRoot, outDir: badOut });
    expect(first.diagnostics).toEqual([]);
    const original = await readFile(join(badOut, "application.ts"), "utf8");

    await writeFixtureProject(badRoot, BAD_PROJECT_FILES);
    const failed = await compileProject({ rootDir: badRoot, outDir: badOut, writeOnError: false });
    expect(failed.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(true);
    expect(failed.written).toEqual([]);
    expect(await readFile(join(badOut, "application.ts"), "utf8")).toBe(original);
  });
});

describe("generate：client.ts 与 permissions.ts 端到端代码生成", () => {
  test("compileProject 带 generateClient 和 generatePermissions 生成 client.ts 与 permissions.ts", async () => {
    const fullOut = join(rootDir, "generated-full");
    const fullResult = await compileProject({
      rootDir,
      outDir: fullOut,
      generateClient: true,
      generatePermissions: true,
    });
    expect(fullResult.diagnostics).toEqual([]);
    expect(fullResult.written).toContain(join(fullOut, "client.ts"));
    expect(fullResult.written).toContain(join(fullOut, "permissions.ts"));

    const clientCode = await readFile(join(fullOut, "client.ts"), "utf8");
    expect(clientCode).toContain("export function createApiClient");
    expect(clientCode).toContain("export const API_ROUTES =");
    expect(clientCode).toContain("case: {");
    expect(clientCode).toContain("accept: (options:");

    const permissionsCode = await readFile(join(fullOut, "permissions.ts"), "utf8");
    expect(permissionsCode).toContain("export const AppPermissions =");
    expect(permissionsCode).toContain('CaseAccept: "case.accept"');
    expect(permissionsCode).toContain("export const RoutePermissions:");
    expect(permissionsCode).toContain("export function hasPermission");

    const clientModule = await import(pathToFileURL(join(fullOut, "client.ts")).href);
    expect(Array.isArray(clientModule.API_ROUTES)).toBe(true);
    expect(clientModule.API_ROUTES[0]).toMatchObject({
      method: "POST",
      path: "/cases/:caseId/accept",
      controller: "CaseController",
      handler: "accept",
    });

    const permissionsModule = await import(pathToFileURL(join(fullOut, "permissions.ts")).href);
    expect(permissionsModule.AppPermissions.CaseAccept).toBe("case.accept");
    expect(permissionsModule.hasPermission(["case.accept"], "case.accept")).toBe(true);
    expect(permissionsModule.hasPermission(["*"], "case.accept")).toBe(true);
    expect(permissionsModule.hasPermission(["other"], "case.accept")).toBe(false);
  });

  test("renderApplication outputs guards and resolvers in controller routes", () => {
    const rendered = renderApplication(
      {
        modules: [
          {
            name: "admin",
            className: "AdminModule",
            file: "src/admin.module.ts",
            line: 1,
            imports: [],
            providers: [],
            controllers: [
              {
                className: "AdminController",
                path: "/admin",
                scope: "request",
                deps: [],
                routes: [
                  {
                    method: "GET",
                    path: "/dashboard",
                    handler: "dashboard",
                    guards: ["authGuard", "roleGuard"],
                    resolvers: { stats: "statsResolver" },
                  },
                ],
                file: "src/admin.controller.ts",
                importPath: "./admin.controller",
              },
            ],
            commands: [],
            queries: [],
            exports: [],
          },
        ],
        externalTokens: [],
      },
      { rootDir: "/app", outDir: "/app/gen", generateClient: true },
    );

    expect(rendered.applicationCode).toContain('guards: ["authGuard","roleGuard"]');
    expect(rendered.applicationCode).toContain('resolvers: {"stats":"statsResolver"}');
    expect(rendered.clientCode).toContain('"guards": [\n      "authGuard",\n      "roleGuard"\n    ]');
  });

  test("compileProject auto-discovers standalone controllers and commands into root module", async () => {
    const standaloneDir = await mkdtemp(join(tmpdir(), "supacloud-standalone-"));
    await writeFixtureProject(standaloneDir, {
      "tsconfig.json": GOOD_PROJECT_FILES["tsconfig.json"],
      "src/standalone.controller.ts": `
        import { Controller, Get, UseGuards } from "@supacloud/app";

        @UseGuards("authGuard")
        @Controller({ path: "/standalone", standalone: true })
        export class StandaloneController {
          @Get("/ping")
          ping() { return "pong"; }
        }
      `,
      "src/standalone.command.ts": `
        import { Command } from "@supacloud/app";

        @Command({ name: "standalone.run", permission: "standalone.run", standalone: true })
        export class StandaloneCommand {}
      `,
    });

    const out = join(standaloneDir, "gen");
    const res = await compileProject({ rootDir: standaloneDir, outDir: out, generateClient: true });
    expect(res.diagnostics).toEqual([]);
    const rootMod = res.graph.modules.find((m) => m.name === "root");
    expect(rootMod).toBeDefined();
    expect(rootMod?.controllers.map((c) => c.className)).toContain("StandaloneController");
    expect(rootMod?.commands.map((c) => c.className)).toContain("StandaloneCommand");

    const appCode = await readFile(join(out, "application.ts"), "utf8");
    expect(appCode).toContain('path: "/standalone"');
    expect(appCode).toContain('guards: ["authGuard"]');
  });
});
