import { afterEach, expect, test } from "bun:test";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";
import { buildSchema, introspectionFromSchema } from "graphql";
import { pullGraphqlSchema } from "./graphql-schema";

const directories: string[] = [];
afterEach(async () => {
  await Promise.all(directories.splice(0).map((path) => rm(path, { force: true, recursive: true })));
});
async function output() {
  const directory = await mkdtemp(join(tmpdir(), "graphql-schema-"));
  directories.push(directory);
  return join(directory, "schema.graphql");
}
const schemaData = introspectionFromSchema(buildSchema("type Query { health: String! }"));

test("exports an explicitly selected caller schema without credentials or a live server", async () => {
  const path = await output();
  const result = await pullGraphqlSchema({
    url: "https://project.example.test",
    output: path,
    publishableKey: "synthetic-public-key",
    accessToken: "synthetic-user-token",
    fetch: async (url, init) => {
      expect(String(url)).toBe("https://project.example.test/graphql/v1");
      expect(new Headers(init?.headers).get("Authorization")).toBe("Bearer synthetic-user-token");
      expect(new Headers(init?.headers).get("apikey")).toBe("synthetic-public-key");
      expect(init?.redirect).toBe("error");
      expect(init?.signal).toBeInstanceOf(AbortSignal);
      expect(JSON.parse(String(init?.body)).operationName).toBe("IntrospectionQuery");
      return Response.json({ data: schemaData });
    },
  });
  expect(result.path).toBe(path);
  expect(result.schemaHash).toMatch(/^[a-f0-9]{64}$/);
  expect(await readFile(path, "utf8")).toContain("health: String!");
  expect(await readFile(path, "utf8")).not.toContain("synthetic");
  const content = await readFile(path, "utf8");
  expect(content).toStartWith("# GENERATED BY supacloud-compiler graphql-schema. DO NOT EDIT.");
  expect(result.schemaHash).toBe(createHash("sha256").update(content).digest("hex"));
});

test.each([
  () => new Response("private", { status: 401 }),
  () => Response.json({ errors: [{ message: "introspection disabled" }] }),
  () => Response.json({ data: null }),
  () => new Response("not JSON"),
])("failed exports preserve the previous schema", async (response) => {
  const path = await output();
  await writeFile(path, "previous schema");
  await expect(pullGraphqlSchema({
    url: "https://project.example.test",
    output: path,
    publishableKey: "public",
    fetch: async () => response(),
  })).rejects.toThrow("GraphQL schema export failed");
  expect(await readFile(path, "utf8")).toBe("previous schema");
});

test("requires explicit identity and does not silently downgrade HTTPS", async () => {
  const path = await output();
  await expect(pullGraphqlSchema({ url: "https://project.example.test", output: path })).rejects.toThrow("explicit caller identity");
  await expect(pullGraphqlSchema({ url: "http://project.example.test", output: path, publishableKey: "public" })).rejects.toThrow("HTTPS");
});

test.each(["schema.ts", "https://project.example.test/schema.graphql"])(
  "export rejects unsupported snapshot target %s before accessing the endpoint",
  async (output) => {
    let requested = false;
    await expect(pullGraphqlSchema({
      url: "https://project.example.test", output, publishableKey: "synthetic-public",
      fetch: async () => {
        requested = true;
        return Response.json({ data: schemaData });
      },
    })).rejects.toThrow("Database First only");
    expect(requested).toBe(false);
  },
);

test("check mode detects missing and changed snapshots without writing", async () => {
  const path = await output();
  let data = schemaData;
  const options = {
    url: "https://project.example.test", output: path, publishableKey: "synthetic-public",
    fetch: async () => Response.json({ data }),
  };
  expect(await pullGraphqlSchema({ ...options, check: true })).toMatchObject({ upToDate: false, written: false });
  await expect(access(path)).rejects.toThrow();
  expect(await pullGraphqlSchema(options)).toMatchObject({ upToDate: true, written: true });
  const previous = await readFile(path, "utf8");
  expect(await pullGraphqlSchema({ ...options, check: true })).toMatchObject({ upToDate: true, written: false });
  data = introspectionFromSchema(buildSchema("type Query { renamedHealth: String! }"));
  expect(await pullGraphqlSchema({ ...options, check: true })).toMatchObject({ upToDate: false, written: false });
  expect(await readFile(path, "utf8")).toBe(previous);
});

test.each([".graphql", ".json"])("manual snapshot edits are detected and an explicit export repairs %s", async (extension) => {
  const path = (await output()).replace(".graphql", extension);
  const options = {
    url: "https://project.example.test", output: path, publishableKey: "synthetic-public",
    fetch: async () => Response.json({ data: schemaData }),
  };
  await pullGraphqlSchema(options);
  const original = await readFile(path, "utf8");
  if (extension === ".json") {
    expect(JSON.parse(original).__schema).toBeDefined();
  } else {
    expect(buildSchema(original).getQueryType()?.getFields().health).toBeDefined();
  }
  const edited = original.replace("health", "inventedField");
  await writeFile(path, edited);
  expect(await pullGraphqlSchema({ ...options, check: true })).toMatchObject({
    upToDate: false, written: false,
  });
  expect(await readFile(path, "utf8")).toBe(edited);
  await pullGraphqlSchema(options);
  expect(await readFile(path, "utf8")).toBe(original);
  expect(await pullGraphqlSchema({ ...options, check: true })).toMatchObject({
    upToDate: true, written: false,
  });
});
