import { mkdir, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { writeFileIfChanged } from "./generate";
import type { IntrospectionQuery } from "graphql";
import { assertGraphqlOptions } from "./graphql-options";

export interface PullGraphqlSchemaOptions {
  /** Explicit project URL. This operation never discovers or changes a deployment. */
  url: string;
  output: string;
  publishableKey?: string;
  accessToken?: string;
  /** Compare the deployed role schema with the snapshot without writing. Useful after migrations. */
  check?: boolean;
  fetch?: (url: string, init: RequestInit) => Promise<Response>;
}

/** Explicit authenticated snapshot export, separate from the offline compile/check pipeline. */
export async function pullGraphqlSchema(options: PullGraphqlSchemaOptions): Promise<{
  path: string;
  schemaHash: string;
  upToDate: boolean;
  written: boolean;
}> {
  assertGraphqlOptions({ schema: options.output });
  const endpoint = new URL(options.url);
  const loopback = ["localhost", "127.0.0.1", "[::1]"].includes(endpoint.hostname);
  if (endpoint.protocol !== "https:" && !(endpoint.protocol === "http:" && loopback)) {
    throw new Error("GraphQL schema export requires HTTPS outside loopback development.");
  }
  if (endpoint.username || endpoint.password || endpoint.search || endpoint.hash) {
    throw new Error("GraphQL project URLs must not contain credentials, query parameters or fragments.");
  }
  if (!options.publishableKey && !options.accessToken) {
    throw new Error("Select an explicit caller identity using a public project key and/or a user access token.");
  }
  endpoint.pathname = endpoint.pathname.replace(/\/$/, "") + "/graphql/v1";
  const { buildClientSchema, getIntrospectionQuery, introspectionFromSchema, lexicographicSortSchema, printSchema } = await import("graphql");
  const headers = new Headers({ "Content-Type": "application/json", Accept: "application/json" });
  if (options.publishableKey) headers.set("apikey", options.publishableKey);
  if (options.accessToken) headers.set("Authorization", `Bearer ${options.accessToken}`);
  const response = await (options.fetch ?? globalThis.fetch)(endpoint.toString(), {
    method: "POST",
    headers,
    body: JSON.stringify({ query: getIntrospectionQuery(), operationName: "IntrospectionQuery" }),
    redirect: "error",
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) throw new Error(`GraphQL schema export failed (HTTP ${response.status}).`);
  let data: IntrospectionQuery;
  try {
    const envelope = await response.json() as { data?: IntrospectionQuery; errors?: unknown[] };
    if (envelope.errors || !envelope.data?.__schema) throw new Error("Missing schema");
    data = envelope.data;
  } catch {
    throw new Error("GraphQL schema export failed. Verify caller grants and enable introspection only in the intended development environment.");
  }
  const schema = lexicographicSortSchema(buildClientSchema(data));
  const path = resolve(options.output);
  const content = path.endsWith(".json")
    ? JSON.stringify(introspectionFromSchema(schema), null, 2) + "\n"
    : "# GENERATED BY supacloud-compiler graphql-schema. DO NOT EDIT.\n"
      + "# Database First: change database declarations, apply migrations, then re-export for the intended role.\n"
      + printSchema(schema) + "\n";
  let previous: string | undefined;
  try {
    previous = await readFile(path, "utf8");
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
  }
  const upToDate = previous === content;
  const schemaHash = createHash("sha256").update(content).digest("hex");
  if (options.check) return { path, schemaHash, upToDate, written: false };
  await mkdir(dirname(path), { recursive: true });
  await writeFileIfChanged(path, content);
  return { path, schemaHash, upToDate: true, written: true };
}
