import { afterEach, describe, expect, test } from "bun:test";
import { appendFile, mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { watchProject } from "./watch";
import { GOOD_PROJECT_FILES } from "./fixtures/good-project";
import { writeFixtureProject } from "./fixtures/helpers";
import type { WatchHandle } from "./types";

let handle: WatchHandle | undefined;

afterEach(async () => {
  await handle?.close();
  handle = undefined;
});

describe("watchProject", () => {
  test("初始编译后，源码变化会触发防抖重编译", async () => {
    const rootDir = await mkdtemp(join(tmpdir(), "supacloud-compiler-watch-"));
    await writeFixtureProject(rootDir, GOOD_PROJECT_FILES);
    const outDir = join(rootDir, "generated");
    const events: string[] = [];
    handle = watchProject({
      rootDir,
      outDir,
      debounceMs: 10,
      onEvent: (event) => events.push(`${event.type}:${event.initial}`),
    });

    const initial = await handle.ready;
    expect(initial.type).toBe("compiled");
    await appendFile(join(rootDir, "src/features/health/health.module.ts"), "\n", "utf8");

    await new Promise<void>((resolvePromise, rejectPromise) => {
      const deadline = setTimeout(() => rejectPromise(new Error("watch compile timed out")), 10_000);
      const interval = setInterval(() => {
        if (events.includes("compiled:false")) {
          clearTimeout(deadline);
          clearInterval(interval);
          resolvePromise();
        }
      }, 20);
    });

    expect(await readFile(join(outDir, "application.ts"), "utf8")).toContain(
      "GENERATED BY @supacloud/compiler",
    );
  }, 20_000);
});
