export { projectRoutes } from "./projects";
export { organizationRoutes } from "./organizations";
export { userRoutes } from "./user";
export { backupRoutes } from "./backups";
export { monitorRoutes } from "./monitor";
export { maintenanceRoutes } from "./maintenance";
export { extensionRoutes } from "./extensions";
export { securityRoutes } from "./security";
export { storageRoutes } from "./storage";
export { scalingRoutes } from "./scaling";
export { taskRoutes } from "./tasks";
export { databaseRoutes } from "./database";
export { authRoutes } from "./auth";
export { frontendRoutes } from "./frontend";
export { webhookRoutes } from "./webhook";
export { studioRoutes, studioAuthRoutes, studioV1Routes } from "./studio";
