_format_version: "2.1"
_transform: true

services:
  - name: edge-runtime
    url: http://edge-runtime:9000
    routes:
      - name: functions-route
        paths:
          - /functions/v1
        strip_path: true

  - name: management-api
    url: http://management-api:9090
    routes:
      - name: management-route
        paths:
          - /platform/v1
        strip_path: true

  - name: gotrue
    url: http://gotrue:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: true

  - name: postgrest
    url: http://postgrest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
        strip_path: true
