import { afterAll, beforeAll, describe, expect, test } from 'bun:test'
import { chmod, mkdir, mkdtemp, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createClient, type RealtimeChannel, type SupabaseClient } from '@supabase/supabase-js'
import { startProjectServer, type RunningProjectServer } from '../src/project-runtime.js'

const migration = `
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy todos_select on public.todos
  for select to authenticated
  using (auth.uid() = user_id);

create policy todos_insert on public.todos
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy todos_update on public.todos
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy todos_delete on public.todos
  for delete to authenticated
  using (auth.uid() = user_id);

create policy assets_select on storage.objects
  for select to authenticated
  using (bucket_id = 'assets' and owner = auth.uid());

create policy assets_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'assets' and owner = auth.uid());

create policy assets_update on storage.objects
  for update to authenticated
  using (bucket_id = 'assets' and owner = auth.uid())
  with check (bucket_id = 'assets' and owner = auth.uid());

create policy assets_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'assets' and owner = auth.uid());

grant usage on schema public to anon, authenticated, service_role;
grant all on public.todos to authenticated, service_role;
grant usage, select on sequence public.todos_id_seq to authenticated, service_role;
`

const functionSource = `
Deno.serve(async (request) => {
  const body = await request.json()
  return new Response(JSON.stringify({
    ok: true,
    name: body.name,
    secret: Deno.env.get('FUNCTION_SECRET')
  }), {
    headers: { 'content-type': 'application/json' }
  })
})
`

let rootDir: string
let project: RunningProjectServer
let anonClient: SupabaseClient
let userClient: SupabaseClient
let serviceClient: SupabaseClient

describe('SupaCloud Lite supabase-js compatibility', () => {
  beforeAll(async () => {
    rootDir = await mkdtemp(join(tmpdir(), 'supacloud-lite-test-'))
    await mkdir(join(rootDir, 'supabase', 'migrations'), { recursive: true })
    await mkdir(join(rootDir, 'supabase', 'functions', 'hello'), { recursive: true })
    await writeFile(join(rootDir, 'supabase', 'migrations', '20260727000000_create_todos.sql'), migration)
    await writeFile(
      join(rootDir, 'supabase', 'config.toml'),
      `[auth.email]\nenable_confirmations = false\n\n[storage.buckets.assets]\npublic = false\n`
    )
    await writeFile(join(rootDir, 'supabase', 'functions', '.env'), 'FUNCTION_SECRET=lite-secret\n')
    await writeFile(join(rootDir, 'supabase', 'functions', 'hello', 'index.ts'), functionSource)

    project = await startProjectServer({ projectDir: rootDir, port: 0, log: () => {} })
    anonClient = createClient(project.url, project.backend.anonKey, clientOptions('bootstrap-user'))
    serviceClient = createClient(project.url, project.backend.serviceRoleKey, clientOptions('service-role'))

    const { data, error } = await anonClient.auth.signUp({
      email: 'lite@example.com',
      password: 'correct-horse-battery-staple',
    })
    expect(error).toBeNull()
    expect(data.session?.access_token).toBeString()
    userClient = anonClient
    anonClient = createClient(project.url, project.backend.anonKey, clientOptions('anonymous'))
  }, 60_000)

  afterAll(async () => {
    await project?.close()
    if (rootDir) await rm(rootDir, { recursive: true, force: true })
  })

  test('exposes a healthy single-project endpoint and protected secrets file', async () => {
    const response = await fetch(`${project.url}/health`)
    expect(response.status).toBe(200)
    expect(await response.json()).toEqual({ name: 'supacloud-lite', project_ref: 'local', status: 'healthy' })

    const secretsPath = join(rootDir, '.supacloud-lite', 'secrets.json')
    await chmod(secretsPath, 0o600)
    expect((await stat(secretsPath)).mode & 0o777).toBe(0o600)
  })

  test('supports Auth sign-in with the official SDK', async () => {
    const signInClient = createClient(project.url, project.backend.anonKey, clientOptions('sign-in-check'))
    const { data, error } = await signInClient.auth.signInWithPassword({
      email: 'lite@example.com',
      password: 'correct-horse-battery-staple',
    })
    expect(error).toBeNull()
    expect(data.user?.email).toBe('lite@example.com')
    expect(data.session?.access_token).toBeString()
  })

  test('supports PostgREST CRUD and PostgreSQL RLS', async () => {
    const inserted = await userClient.from('todos').insert({ title: 'ship lite' }).select().single()
    expect(inserted.error).toBeNull()
    expect(inserted.data.title).toBe('ship lite')

    expect((await anonClient.auth.getSession()).data.session).toBeNull()
    const anonymousRows = await anonClient.from('todos').select('*')
    expect(anonymousRows.error).toBeNull()
    expect(anonymousRows.data).toEqual([])

    const updated = await userClient.from('todos').update({ done: true }).eq('id', inserted.data.id).select().single()
    expect(updated.error).toBeNull()
    expect(updated.data.done).toBe(true)

    const serviceRows = await serviceClient.from('todos').select('*').eq('id', inserted.data.id)
    expect(serviceRows.error).toBeNull()
    expect(serviceRows.data).toHaveLength(1)

    const removed = await userClient.from('todos').delete().eq('id', inserted.data.id)
    expect(removed.error).toBeNull()
  })

  test('supports Storage upload, download, list, and remove', async () => {
    const payload = new TextEncoder().encode('hello from lite')
    const upload = await userClient.storage.from('assets').upload('docs/hello.txt', payload, {
      contentType: 'text/plain',
      upsert: true,
    })
    expect(upload.error).toBeNull()

    const listed = await userClient.storage.from('assets').list('docs')
    expect(listed.error).toBeNull()
    expect(listed.data?.map((item) => item.name)).toContain('hello.txt')

    const downloaded = await userClient.storage.from('assets').download('docs/hello.txt')
    expect(downloaded.error).toBeNull()
    expect(await downloaded.data!.text()).toBe('hello from lite')

    const removed = await userClient.storage.from('assets').remove(['docs/hello.txt'])
    expect(removed.error).toBeNull()
  })

  test('supports Edge Functions invoke through Bun.build bundles', async () => {
    const result = await userClient.functions.invoke('hello', { body: { name: 'SupaCloud' } })
    expect(result.error).toBeNull()
    expect(result.data).toEqual({ ok: true, name: 'SupaCloud', secret: 'lite-secret' })
  })

  test('supports Realtime postgres_changes through Bun WebSockets', async () => {
    let channel: RealtimeChannel | undefined
    try {
      const eventPromise = new Promise<Record<string, unknown>>((resolveEvent, rejectEvent) => {
        const timeout = setTimeout(() => rejectEvent(new Error('realtime event timeout')), 10_000)
        channel = userClient
          .channel('todos-changes')
          .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'todos' }, (payload) => {
            clearTimeout(timeout)
            resolveEvent(payload.new as Record<string, unknown>)
          })
          .subscribe(async (status) => {
            if (status === 'SUBSCRIBED') {
              const inserted = await userClient.from('todos').insert({ title: 'realtime todo' })
              if (inserted.error) rejectEvent(inserted.error)
            }
            if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
              clearTimeout(timeout)
              rejectEvent(new Error(`realtime channel status: ${status}`))
            }
          })
      })
      expect((await eventPromise).title).toBe('realtime todo')
    } finally {
      if (channel) await userClient.removeChannel(channel)
    }
  }, 20_000)
})

function clientOptions(storageKey: string) {
  return {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false, storageKey },
    realtime: { params: { eventsPerSecond: 20 } },
  }
}
