import { afterAll, beforeAll, describe, expect, test } from 'bun:test'
import { mkdir, mkdtemp, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createClient, type RealtimeChannel, type SupabaseClient } from '@supabase/supabase-js'
import { startProjectServer, type RunningProjectServer } from '../src/project-runtime.js'
import { BOOTSTRAP_SQL } from '../src/runtime/db/bootstrap.js'

const migration = `
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  title text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.todos enable row level security;

create policy todos_select on public.todos
  for select to authenticated
  using (auth.uid() = user_id);

create policy todos_insert on public.todos
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy todos_update on public.todos
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy todos_delete on public.todos
  for delete to authenticated
  using (auth.uid() = user_id);

create table public.realtime_secrets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  secret text not null
);

alter table public.realtime_secrets enable row level security;

create policy realtime_secrets_select on public.realtime_secrets
  for select to authenticated
  using (auth.uid() = owner_id);

-- Exercise both the legacy UUID owner and the current Storage API owner_id.
create policy assets_select on storage.objects
  for select to authenticated
  using (bucket_id = 'assets' and owner = auth.uid() and owner_id = auth.uid()::text);

create policy assets_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'assets' and owner = auth.uid() and owner_id = auth.uid()::text);

create policy assets_update on storage.objects
  for update to authenticated
  using (bucket_id = 'assets' and owner = auth.uid() and owner_id = auth.uid()::text)
  with check (bucket_id = 'assets' and owner = auth.uid() and owner_id = auth.uid()::text);

create policy assets_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'assets' and owner = auth.uid() and owner_id = auth.uid()::text);

grant usage on schema public to anon, authenticated, service_role;
grant all on public.todos to authenticated, service_role;
grant all on public.realtime_secrets to authenticated, service_role;
grant usage, select on sequence public.todos_id_seq to authenticated, service_role;

create function public.authenticated_only_rpc() returns boolean
  language sql stable
  as $$ select true $$;

revoke all on function public.authenticated_only_rpc() from public;
grant execute on function public.authenticated_only_rpc() to authenticated;
`

const functionSource = `
Deno.serve(async (request) => {
  const body = await request.json()
  return new Response(JSON.stringify({
    ok: true,
    name: body.name,
    secret: Deno.env.get('FUNCTION_SECRET')
  }), {
    headers: { 'content-type': 'application/json' }
  })
})
`

let rootDir: string
let project: RunningProjectServer
let anonClient: SupabaseClient
let userClient: SupabaseClient
let serviceClient: SupabaseClient
let userAccessToken: string
let userId: string

describe('SupaCloud Lite supabase-js compatibility', () => {
  beforeAll(async () => {
    rootDir = await mkdtemp(join(tmpdir(), 'supacloud-lite-test-'))
    await mkdir(join(rootDir, 'supabase', 'migrations'), { recursive: true })
    await mkdir(join(rootDir, 'supabase', 'functions', 'hello'), { recursive: true })
    await writeFile(join(rootDir, 'supabase', 'migrations', '20260727000000_create_todos.sql'), migration)
    await writeFile(
      join(rootDir, 'supabase', 'config.toml'),
      `[auth.email]\nenable_confirmations = false\n\n[storage]\nfile_size_limit = "16B"\n\n[storage.buckets.assets]\npublic = false\nallowed_mime_types = ["text/plain"]\n\n[functions.hello]\nverify_jwt = false\n`
    )
    await writeFile(join(rootDir, 'supabase', 'functions', '.env'), 'FUNCTION_SECRET=lite-secret\n')
    await writeFile(join(rootDir, 'supabase', 'functions', 'hello', 'index.ts'), functionSource)

    project = await startProjectServer({ projectDir: rootDir, port: 0, log: () => {} })
    anonClient = createClient(project.url, project.backend.anonKey, clientOptions('bootstrap-user'))
    serviceClient = createClient(project.url, project.backend.serviceRoleKey, clientOptions('service-role'))

    const { data, error } = await anonClient.auth.signUp({
      email: 'lite@example.com',
      password: 'correct-horse-battery-staple',
    })
    expect(error).toBeNull()
    expect(data.session?.access_token).toBeString()
    userId = data.user!.id
    userAccessToken = data.session!.access_token
    userClient = anonClient
    anonClient = createClient(project.url, project.backend.anonKey, clientOptions('anonymous'))
  }, 60_000)

  afterAll(async () => {
    await project?.close()
    if (rootDir) await rm(rootDir, { recursive: true, force: true })
  })

  test('exposes a healthy single-project endpoint and secrets file', async () => {
    const response = await fetch(`${project.url}/health`)
    expect(response.status).toBe(200)
    expect(await response.json()).toEqual({ name: 'supacloud-lite', project_ref: 'local', status: 'healthy' })

    const secretsPath = join(rootDir, '.supacloud-lite', 'secrets.json')
    const secretsFile = await stat(secretsPath)
    expect(secretsFile.isFile()).toBe(true)
    if (process.platform !== 'win32') expect(secretsFile.mode & 0o777).toBe(0o600)
  })

  test('supports Auth sign-in with the official SDK', async () => {
    const signInClient = createClient(project.url, project.backend.anonKey, clientOptions('sign-in-check'))
    const { data, error } = await signInClient.auth.signInWithPassword({
      email: 'lite@example.com',
      password: 'correct-horse-battery-staple',
    })
    expect(error).toBeNull()
    expect(data.user?.email).toBe('lite@example.com')
    expect(data.session?.access_token).toBeString()
  })

  test('honors project-defined RPC execution grants', async () => {
    await expectRpcAllowed(userClient)
    await expectRpcDenied(anonClient)
    await expectRpcDenied(serviceClient)
  })

  test('preserves explicit RPC grants when bootstrapping persistent state', async () => {
    await project.backend.db.exec(`
      revoke all on function public.authenticated_only_rpc() from public, anon, authenticated, service_role;
      grant execute on function public.authenticated_only_rpc() to anon;
    `)
    try {
      await project.backend.db.exec(BOOTSTRAP_SQL)
      project.backend.db.invalidateSchemaCache()

      await expectRpcAllowed(anonClient)
      await expectRpcDenied(userClient)
      await expectRpcDenied(serviceClient)
    } finally {
      await project.backend.db.exec(`
        revoke all on function public.authenticated_only_rpc() from public, anon, authenticated, service_role;
        grant execute on function public.authenticated_only_rpc() to authenticated;
      `)
    }
  })

  test('supports PostgREST CRUD and PostgreSQL RLS', async () => {
    const inserted = await userClient.from('todos').insert({ title: 'ship lite' }).select().single()
    expect(inserted.error).toBeNull()
    expect(inserted.data.title).toBe('ship lite')

    expect((await anonClient.auth.getSession()).data.session).toBeNull()
    const anonymousRows = await anonClient.from('todos').select('*')
    expect(anonymousRows.error).toBeNull()
    expect(anonymousRows.data).toEqual([])

    const updated = await userClient.from('todos').update({ done: true }).eq('id', inserted.data.id).select().single()
    expect(updated.error).toBeNull()
    expect(updated.data.done).toBe(true)

    const serviceRows = await serviceClient.from('todos').select('*').eq('id', inserted.data.id)
    expect(serviceRows.error).toBeNull()
    expect(serviceRows.data).toHaveLength(1)

    const removed = await userClient.from('todos').delete().eq('id', inserted.data.id)
    expect(removed.error).toBeNull()
  })

  test('supports Storage upload, download, list, and remove', async () => {
    const payload = new TextEncoder().encode('hello from lite')
    const upload = await userClient.storage.from('assets').upload('docs/hello.txt', payload, {
      contentType: 'text/plain',
      upsert: true,
    })
    expect(upload.error).toBeNull()
    await expectStoredOwner('docs/hello.txt')

    const upserted = await userClient.storage.from('assets').upload('docs/hello.txt', 'updated', {
      contentType: 'text/plain',
      upsert: true,
    })
    expect(upserted.error).toBeNull()
    await expectStoredOwner('docs/hello.txt')

    const copied = await userClient.storage.from('assets').copy('docs/hello.txt', 'docs/copied.txt')
    expect(copied.error).toBeNull()
    await expectStoredOwner('docs/copied.txt')

    const oversized = await userClient.storage.from('assets').upload('docs/oversized.txt', 'x'.repeat(64 * 1024), {
      contentType: 'text/plain',
      upsert: true,
    })
    expect(oversized.error).not.toBeNull()

    const reservedBucket = await serviceClient.storage.createBucket('.supacloud-lite')
    expect(reservedBucket.error).not.toBeNull()
    const reservedPrefixBucket = await serviceClient.storage.createBucket('.supacloud-lite/objects')
    expect(reservedPrefixBucket.error).not.toBeNull()

    const listed = await userClient.storage.from('assets').list('docs')
    expect(listed.error).toBeNull()
    expect(listed.data?.map((item) => item.name)).toContain('hello.txt')

    const downloaded = await userClient.storage.from('assets').download('docs/hello.txt')
    expect(downloaded.error).toBeNull()
    expect(await downloaded.data!.text()).toBe('updated')

    const removed = await userClient.storage.from('assets').remove(['docs/hello.txt', 'docs/copied.txt'])
    expect(removed.error).toBeNull()
  })

  test('supports Edge Functions invoke through Bun.build bundles', async () => {
    const result = await userClient.functions.invoke('hello', { body: { name: 'SupaCloud' } })
    expect(result.error).toBeNull()
    expect(result.data).toEqual({ ok: true, name: 'SupaCloud', secret: 'lite-secret' })

    const publicResponse = await fetch(`${project.url}/functions/v1/hello`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ name: 'Public' }),
    })
    expect(publicResponse.status).toBe(200)
    expect(await publicResponse.json()).toEqual({ ok: true, name: 'Public', secret: 'lite-secret' })
  })

  test('enforces TUS limits and RLS before buffering upload data', async () => {
    const oversized = await createTusUpload(1024, userAccessToken, 'oversized.bin')
    expect(oversized.status).toBe(413)

    const unauthorized = await createTusUpload(5, project.backend.anonKey, 'anonymous.txt')
    expect(unauthorized.status).toBe(403)

    expect((await createTusUpload(1, userAccessToken, '../escape.txt')).status).toBe(400)
    expect((await createTusUpload(1, userAccessToken, 'image.png', 'image/png')).status).toBe(415)

    for (let index = 0; index < 5; index++) {
      const key = `empty-${index}.txt`
      const emptyUpload = await createTusUpload(0, userAccessToken, key)
      expect(emptyUpload.status).toBe(201)
      if (index === 0) {
        const location = emptyUpload.headers.get('location')
        expect(location).toBeString()
        const head = await fetch(location!, {
          method: 'HEAD',
          headers: {
            apikey: project.backend.anonKey,
            authorization: `Bearer ${userAccessToken}`,
            'tus-resumable': '1.0.0',
          },
        })
        expect(head.status).toBe(200)
        expect(head.headers.get('upload-length')).toBe('0')
      }
      expect(await (await userClient.storage.from('assets').download(key)).data!.text()).toBe('')
    }

    const created = await createTusUpload(5, userAccessToken, 'resumable.txt')
    expect(created.status).toBe(201)
    const location = created.headers.get('location')
    expect(location).toBeString()
    const patched = await fetch(location!, {
      method: 'PATCH',
      headers: {
        apikey: project.backend.anonKey,
        authorization: `Bearer ${userAccessToken}`,
        'content-type': 'application/offset+octet-stream',
        'tus-resumable': '1.0.0',
        'upload-offset': '0',
      },
      body: 'hello',
    })
    expect(patched.status).toBe(204)
    const downloaded = await userClient.storage.from('assets').download('resumable.txt')
    expect(downloaded.error).toBeNull()
    expect(await downloaded.data!.text()).toBe('hello')
    await expectStoredOwner('resumable.txt')
  })

  test('rejects unsafe TUS object paths and disallowed MIME types before upload allocation', async () => {
    expect((await createTusUpload(5, userAccessToken, '../escape.txt')).status).toBe(400)
    expect((await createTusUpload(5, userAccessToken, 'payload.json', 'application/json')).status).toBe(415)
    const oversizedChunk = await fetch(`${project.url}/storage/v1/upload/resumable`, {
      method: 'POST',
      headers: {
        apikey: project.backend.anonKey,
        authorization: `Bearer ${userAccessToken}`,
        'content-type': 'application/offset+octet-stream',
        'tus-resumable': '1.0.0',
        'upload-length': '1',
        'upload-metadata': [
          `bucketName ${btoa('assets')}`,
          `objectName ${btoa('bounded.txt')}`,
          `contentType ${btoa('text/plain')}`,
        ].join(','),
      },
      body: 'x'.repeat(64 * 1024),
    })
    expect(oversizedChunk.status).toBe(400)

    const metadata = [
      `bucketName ${btoa('assets')}`,
      `objectName ${btoa('strict.txt')}`,
      `contentType ${btoa('text/plain')}`,
    ].join(',')
    const missingVersion = await fetch(`${project.url}/storage/v1/upload/resumable`, {
      method: 'POST',
      headers: {
        apikey: project.backend.anonKey,
        authorization: `Bearer ${userAccessToken}`,
        'upload-length': '1',
        'upload-metadata': metadata,
      },
    })
    expect(missingVersion.status).toBe(412)
    const malformedLength = await fetch(`${project.url}/storage/v1/upload/resumable`, {
      method: 'POST',
      headers: {
        apikey: project.backend.anonKey,
        authorization: `Bearer ${userAccessToken}`,
        'tus-resumable': '1.0.0',
        'upload-length': '1junk',
        'upload-metadata': metadata,
      },
    })
    expect(malformedLength.status).toBe(400)
    expect((await createTusUpload(0, userAccessToken, 'case-insensitive.txt', 'Text/Plain')).status).toBe(201)
  })

  test('supports Realtime postgres_changes through Bun WebSockets', async () => {
    let channel: RealtimeChannel | undefined
    try {
      const eventPromise = new Promise<Record<string, unknown>>((resolveEvent, rejectEvent) => {
        const timeout = setTimeout(() => rejectEvent(new Error('realtime event timeout')), 10_000)
        channel = userClient
          .channel('todos-changes')
          .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'todos' }, (payload) => {
            clearTimeout(timeout)
            resolveEvent(payload.new as Record<string, unknown>)
          })
          .subscribe(async (status) => {
            if (status === 'SUBSCRIBED') {
              const inserted = await userClient.from('todos').insert({ title: 'realtime todo' })
              if (inserted.error) rejectEvent(inserted.error)
            }
            if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
              clearTimeout(timeout)
              rejectEvent(new Error(`realtime channel status: ${status}`))
            }
          })
      })
      expect((await eventPromise).title).toBe('realtime todo')
    } finally {
      if (channel) await userClient.removeChannel(channel)
    }
  }, 20_000)

  test('does not leak RLS-protected DELETE events to ordinary subscribers', async () => {
    const secondAuth = createClient(project.url, project.backend.anonKey, clientOptions('delete-observer'))
    const second = await secondAuth.auth.signUp({
      email: 'observer@example.com',
      password: 'correct-horse-battery-staple',
    })
    expect(second.error).toBeNull()

    let channel: RealtimeChannel | undefined
    try {
      const leaked = await new Promise<boolean>((resolveLeak, rejectLeak) => {
        const timeout = setTimeout(() => resolveLeak(false), 750)
        channel = secondAuth
          .channel('delete-observer')
          .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'todos' }, () => {
            clearTimeout(timeout)
            resolveLeak(true)
          })
          .subscribe(async (status) => {
            if (status === 'SUBSCRIBED') {
              const inserted = await userClient.from('todos').insert({ title: 'private delete' }).select().single()
              if (inserted.error) rejectLeak(inserted.error)
              const deleted = await userClient.from('todos').delete().eq('id', inserted.data.id)
              if (deleted.error) rejectLeak(deleted.error)
            }
            if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
              clearTimeout(timeout)
              rejectLeak(new Error(`realtime channel status: ${status}`))
            }
          })
      })
      expect(leaked).toBe(false)
    } finally {
      if (channel) await secondAuth.removeChannel(channel)
    }
  }, 20_000)

  test('does not authorize an old RLS event from a newer row state', async () => {
    const other = await serviceClient.auth.admin.createUser({
      email: 'snapshot-owner@example.com',
      password: 'correct-horse-battery-staple',
      email_confirm: true,
    })
    expect(other.error).toBeNull()
    const otherUser = other.data.user
    if (!otherUser) throw new Error('admin createUser returned no user')

    let channel: RealtimeChannel | undefined
    try {
      const result = await new Promise<{ leaked: boolean; receivedCurrent: boolean }>((resolveResult, rejectLeak) => {
        let receivedCurrent = false
        const timeout = setTimeout(() => resolveResult({ leaked: false, receivedCurrent }), 1_000)
        channel = userClient
          .channel('realtime-snapshot')
          .on('postgres_changes', { event: '*', schema: 'public', table: 'realtime_secrets' }, (payload) => {
            const secret = (payload.new as { secret?: string }).secret
            if (secret === 'private-before-transfer') {
              clearTimeout(timeout)
              resolveResult({ leaked: true, receivedCurrent })
            }
            if (secret === 'public-after-transfer') receivedCurrent = true
          })
          .subscribe(async (status) => {
            if (status === 'SUBSCRIBED') {
              try {
                await project.backend.db.exec(`
                  begin;
                  insert into public.realtime_secrets (owner_id, secret)
                  values ('${otherUser.id}', 'private-before-transfer');
                  update public.realtime_secrets
                  set owner_id = '${userId}', secret = 'public-after-transfer';
                  commit;
                `)
              } catch (error) {
                clearTimeout(timeout)
                rejectLeak(error)
              }
            }
            if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
              clearTimeout(timeout)
              rejectLeak(new Error(`realtime channel status: ${status}`))
            }
          })
      })
      expect(result.leaked).toBe(false)
      expect(result.receivedCurrent).toBe(true)
    } finally {
      if (channel) await userClient.removeChannel(channel)
    }
  }, 20_000)
})

function clientOptions(storageKey: string) {
  return {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false, storageKey },
    realtime: { params: { eventsPerSecond: 20 } },
  }
}

async function expectStoredOwner(key: string): Promise<void> {
  const stored = await project.backend.db.query<{ owner: string; owner_id: string }>(
    `select owner, owner_id from storage.objects where bucket_id = 'assets' and name = $1`,
    [key]
  )
  expect(stored.rows[0]).toEqual({ owner: userId, owner_id: userId })
}

async function expectRpcAllowed(client: SupabaseClient): Promise<void> {
  const call = await client.rpc('authenticated_only_rpc')
  expect(call.error).toBeNull()
  expect(call.data).toBe(true)
}

async function expectRpcDenied(client: SupabaseClient): Promise<void> {
  const call = await client.rpc('authenticated_only_rpc')
  expect(call.data).toBeNull()
  expect(call.error?.code).toBe('42501')
}

function createTusUpload(length: number, token: string, key: string, contentType = 'text/plain'): Promise<Response> {
  const metadata = [
    `bucketName ${btoa('assets')}`,
    `objectName ${btoa(key)}`,
    `contentType ${btoa(contentType)}`,
  ].join(',')
  return fetch(`${project.url}/storage/v1/upload/resumable`, {
    method: 'POST',
    headers: {
      apikey: project.backend.anonKey,
      authorization: `Bearer ${token}`,
      'tus-resumable': '1.0.0',
      'upload-length': String(length),
      'upload-metadata': metadata,
    },
  })
}
