import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createBackend } from '../src/runtime/index.js'
import { diffSchemas, snapshotSchema } from '../src/runtime/db/schema-diff.js'

const temporaryDirectories: string[] = []
const initialMigration = {
  name: '20260814000000_initial',
  sql: `
    create table public.migration_items (
      id bigint generated by default as identity primary key,
      name text not null
    );
    grant all on public.migration_items to service_role;
  `,
}
const upgradeMigration = {
  name: '20260814000100_upgrade',
  sql: `
    alter table public.migration_items add column enabled boolean not null default true;
    create index migration_items_enabled_idx on public.migration_items (enabled);
  `,
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })))
})

describe('migration parity', () => {
  test('produces the same schema from fresh install and incremental upgrade', async () => {
    const upgradeRoot = await mkdtemp(join(tmpdir(), 'supacloud-lite-migration-upgrade-'))
    temporaryDirectories.push(upgradeRoot)
    const dataDir = join(upgradeRoot, 'db')
    const initial = await createBackend({ dataDir, migrations: [initialMigration], startRuntimeServices: false })
    await initial.db.query('insert into public.migration_items (name) values ($1)', ['preserved'])
    await initial.close()

    const upgraded = await createBackend({
      dataDir,
      migrations: [initialMigration, upgradeMigration],
      startRuntimeServices: false,
    })
    const fresh = await createBackend({ migrations: [initialMigration, upgradeMigration], startRuntimeServices: false })
    try {
      const upgradedSchema = await snapshotSchema(upgraded.db, 'public')
      const freshSchema = await snapshotSchema(fresh.db, 'public')
      expect(diffSchemas(upgradedSchema, freshSchema, 'public')).toEqual([])
      expect(diffSchemas(freshSchema, upgradedSchema, 'public')).toEqual([])
      expect((await upgraded.db.query('select name, enabled from public.migration_items')).rows).toEqual([
        { name: 'preserved', enabled: true },
      ])
      expect((await upgraded.db.listAppliedMigrations()).map((migration) => migration.version)).toEqual([
        '20260814000000',
        '20260814000100',
      ])
    } finally {
      await Promise.all([upgraded.close(), fresh.close()])
    }
  })

  test('rolls back and leaves a failed migration unrecorded', async () => {
    const backend = await createBackend({ migrations: [initialMigration], startRuntimeServices: false })
    try {
      await expect(backend.db.runMigrations([{
        name: '20260814000200_broken',
        sql: `alter table public.migration_items add column temporary text; select missing_function();`,
      }])).rejects.toThrow()
      const columns = await backend.db.query<{ column_name: string }>(
        `select column_name from information_schema.columns where table_schema = 'public' and table_name = 'migration_items'`
      )
      expect(columns.rows.map((column) => column.column_name)).not.toContain('temporary')
      expect((await backend.db.listAppliedMigrations()).map((migration) => migration.version)).toEqual(['20260814000000'])
    } finally {
      await backend.close()
    }
  })
})
