import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createBackend } from '../src/runtime/index.js'
import { createNativeEngine, isNativeEngineSupported } from '../src/runtime/node/native/engine.js'
import { buildWireEngine } from '../src/runtime/node/native/wire-engine.js'
import { decodeValue, parsePgArray, type PgWireClient } from '../src/runtime/node/native/wire.js'

const nativeIntegrationEnabled = process.env.SUPACLOUD_LITE_TEST_NATIVE === '1' && isNativeEngineSupported()
const temporaryDirectories: string[] = []

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })))
})

describe('native PostgreSQL wire decoding', () => {
  test('preserves scalar and array value semantics', () => {
    expect(decodeValue('t', 16)).toBe(true)
    expect(decodeValue('9007199254740993', 20)).toBe('9007199254740993')
    expect(decodeValue('{1,NULL,9007199254740993}', 1016)).toEqual([1, null, '9007199254740993'])
    expect(parsePgArray('{plain,"with space",NULL,"escaped\\"quote"}')).toEqual([
      'plain',
      'with space',
      null,
      'escaped"quote',
    ])
  })

  test('retries LISTEN after the first server command fails', async () => {
    const queryClient = wireClient()
    const listenerClient = wireClient()
    let listenAttempts = 0
    listenerClient.exec = async () => {
      listenAttempts += 1
      if (listenAttempts === 1) throw new Error('temporary LISTEN failure')
      return []
    }
    const clients = [queryClient, listenerClient]
    const engine = await buildWireEngine({ connect: async () => clients.shift()! })

    await expect(engine.listen('retry_channel', () => {})).rejects.toThrow('temporary LISTEN failure')
    const unsubscribe = await engine.listen('retry_channel', () => {})

    expect(listenAttempts).toBe(2)
    await unsubscribe()
    await engine.close()
  })

  test('keeps concurrent first listeners on the same channel', async () => {
    const queryClient = wireClient()
    const listenerClient = wireClient()
    let listenCommands = 0
    listenerClient.exec = async () => {
      listenCommands += 1
      await Bun.sleep(5)
      return []
    }
    const clients = [queryClient, listenerClient]
    const engine = await buildWireEngine({ connect: async () => clients.shift()! })
    let firstNotifications = 0
    let secondNotifications = 0

    const [unsubscribeFirst, unsubscribeSecond] = await Promise.all([
      engine.listen('shared_channel', () => { firstNotifications += 1 }),
      engine.listen('shared_channel', () => { secondNotifications += 1 }),
    ])
    listenerClient.onNotification?.('shared_channel', 'ready')

    expect(listenCommands).toBe(1)
    expect([firstNotifications, secondNotifications]).toEqual([1, 1])
    await Promise.all([unsubscribeFirst(), unsubscribeSecond()])
    await engine.close()
  })
})

describe.skipIf(!nativeIntegrationEnabled)('native PostgreSQL engine', () => {
  test('runs migrations, RLS context, transactions, and notifications', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'supacloud-lite-native-'))
    temporaryDirectories.push(projectRoot)
    const engine = await createNativeEngine({ dataDir: join(projectRoot, 'pgdata') })
    const backend = await createBackend({
      engine,
      migrations: [{
        name: '20260814000000_native',
        sql: `
          create table public.native_notes (id bigint generated by default as identity primary key, body text not null);
          grant all on public.native_notes to anon, authenticated, service_role;
          grant usage, select on sequence public.native_notes_id_seq to anon, authenticated, service_role;
        `,
      }],
      startRuntimeServices: false,
    })
    try {
      const inserted = await backend.db.query<{ id: number; body: string }>(
        'insert into public.native_notes (body) values ($1) returning id, body',
        ['native']
      )
      expect(inserted.rows).toEqual([{ id: 1, body: 'native' }])
      expect((await backend.db.query('select current_setting(\'timezone\') as timezone')).rows).toEqual([
        { timezone: 'UTC' },
      ])
      await expect(
        backend.db.transaction(async (query) => {
          await query('insert into public.native_notes (body) values ($1)', ['rolled-back'])
          throw new Error('rollback')
        })
      ).rejects.toThrow('rollback')
      expect((await backend.db.query('select * from public.native_notes order by id')).rows).toHaveLength(1)

      let resolveNotification!: (payload: string) => void
      const notification = new Promise<string>((resolve) => (resolveNotification = resolve))
      const unsubscribe = await backend.db.engine.listen('native_test', resolveNotification)
      await backend.db.exec(`select pg_notify('native_test', 'ready')`)
      expect(await notification).toBe('ready')
      await unsubscribe()
    } finally {
      await backend.close()
    }
  }, 120_000)
})

function wireClient(): PgWireClient {
  return {
    onNotification: null,
    query: async () => ({ rows: [] }),
    exec: async () => [],
    close: async () => undefined,
  } as unknown as PgWireClient
}
