import { afterEach, describe, expect, test } from 'bun:test'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createBackend } from '../src/runtime/index.js'
import { createNativeEngine, isNativeEngineSupported } from '../src/runtime/node/native/engine.js'
import { ensurePowerSyncReplicationCatalog } from '../src/runtime/node/native/replication.js'
import { inspectPowerSyncReadiness } from '../src/runtime/node/native/readiness.js'
import { buildWireEngine } from '../src/runtime/node/native/wire-engine.js'
import { decodeValue, parsePgArray, PgWireClient } from '../src/runtime/node/native/wire.js'

const nativeIntegrationEnabled = process.env.SUPACLOUD_LITE_TEST_NATIVE === '1' && isNativeEngineSupported()
const temporaryDirectories: string[] = []

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })))
})

describe('native PostgreSQL wire decoding', () => {
  test('preserves scalar and array value semantics', () => {
    expect(decodeValue('t', 16)).toBe(true)
    expect(decodeValue('9007199254740993', 20)).toBe('9007199254740993')
    expect(decodeValue('{1,NULL,9007199254740993}', 1016)).toEqual([1, null, '9007199254740993'])
    expect(parsePgArray('{plain,"with space",NULL,"escaped\\"quote"}')).toEqual([
      'plain',
      'with space',
      null,
      'escaped"quote',
    ])
  })

  test('retries LISTEN after the first server command fails', async () => {
    const queryClient = wireClient()
    const listenerClient = wireClient()
    let listenAttempts = 0
    listenerClient.exec = async () => {
      listenAttempts += 1
      if (listenAttempts === 1) throw new Error('temporary LISTEN failure')
      return []
    }
    const clients = [queryClient, listenerClient]
    const engine = await buildWireEngine({ connect: async () => clients.shift()! })

    await expect(engine.listen('retry_channel', () => {})).rejects.toThrow('temporary LISTEN failure')
    const unsubscribe = await engine.listen('retry_channel', () => {})

    expect(listenAttempts).toBe(2)
    await unsubscribe()
    await engine.close()
  })

  test('keeps concurrent first listeners on the same channel', async () => {
    const queryClient = wireClient()
    const listenerClient = wireClient()
    let listenCommands = 0
    listenerClient.exec = async () => {
      listenCommands += 1
      await Bun.sleep(5)
      return []
    }
    const clients = [queryClient, listenerClient]
    const engine = await buildWireEngine({ connect: async () => clients.shift()! })
    let firstNotifications = 0
    let secondNotifications = 0

    const [unsubscribeFirst, unsubscribeSecond] = await Promise.all([
      engine.listen('shared_channel', () => { firstNotifications += 1 }),
      engine.listen('shared_channel', () => { secondNotifications += 1 }),
    ])
    listenerClient.onNotification?.('shared_channel', 'ready')

    expect(listenCommands).toBe(1)
    expect([firstNotifications, secondNotifications]).toEqual([1, 1])
    await Promise.all([unsubscribeFirst(), unsubscribeSecond()])
    await engine.close()
  })
})

describe.skipIf(!nativeIntegrationEnabled)('native PostgreSQL engine', () => {
  test('runs migrations, RLS context, transactions, and notifications', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'supacloud-lite-native-'))
    temporaryDirectories.push(projectRoot)
    const engine = await createNativeEngine({ dataDir: join(projectRoot, 'pgdata') })
    const backend = await createBackend({
      engine,
      migrations: [{
        name: '20260814000000_native',
        sql: `
          create table public.native_notes (id bigint generated by default as identity primary key, body text not null);
          grant all on public.native_notes to anon, authenticated, service_role;
          grant usage, select on sequence public.native_notes_id_seq to anon, authenticated, service_role;
        `,
      }],
      startRuntimeServices: false,
    })
    try {
      const inserted = await backend.db.query<{ id: number; body: string }>(
        'insert into public.native_notes (body) values ($1) returning id, body',
        ['native']
      )
      expect(inserted.rows).toEqual([{ id: 1, body: 'native' }])
      expect((await backend.db.query('select current_setting(\'timezone\') as timezone')).rows).toEqual([
        { timezone: 'UTC' },
      ])
      await expect(
        backend.db.transaction(async (query) => {
          await query('insert into public.native_notes (body) values ($1)', ['rolled-back'])
          throw new Error('rollback')
        })
      ).rejects.toThrow('rollback')
      expect((await backend.db.query('select * from public.native_notes order by id')).rows).toHaveLength(1)

      let resolveNotification!: (payload: string) => void
      const notification = new Promise<string>((resolve) => (resolveNotification = resolve))
      const unsubscribe = await backend.db.engine.listen('native_test', resolveNotification)
      await backend.db.exec(`select pg_notify('native_test', 'ready')`)
      expect(await notification).toBe('ready')
      await unsubscribe()
    } finally {
      await backend.close()
    }
  }, 120_000)

  test('enables a bounded PowerSync source only through the explicit profile', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'supacloud-lite-native-powersync-'))
    temporaryDirectories.push(projectRoot)
    const port = await freePort()
    const password = `powersync-${crypto.randomUUID()}-${crypto.randomUUID()}`
    const replication = {
      profile: 'powersync' as const,
      host: '127.0.0.1',
      port,
      allowCidrs: ['127.0.0.1/32'],
      publicationTables: ['public.lab_entries'],
      password,
    }
    const engine = await createNativeEngine({ dataDir: join(projectRoot, 'pgdata'), replication })
    const backend = await createBackend({
      engine,
      migrations: [{
        name: '20260820010000_powersync_source',
        sql: `
          create table public.lab_entries (
            id uuid primary key default gen_random_uuid(),
            payload jsonb not null default '{}'::jsonb
          );
        `,
      }],
      startRuntimeServices: false,
    })
    try {
      await ensurePowerSyncReplicationCatalog(backend.db.engine, replication)
      const readiness = await inspectPowerSyncReadiness(backend.db.engine, replication)
      expect(readiness).toMatchObject({
        ready: true,
        blockers: [],
        wal: {
          level: 'logical',
          max_senders: 4,
          max_replication_slots: 4,
          used_replication_slots: 0,
          max_slot_wal_keep_size: '1024',
        },
        role: {
          name: 'supacloud_powersync',
          present: true,
          login: true,
          replication: true,
          bypass_rls: true,
        },
        publication: {
          name: 'powersync',
          present: true,
          all_tables: false,
          tables: ['public.lab_entries'],
          expected_tables: ['public.lab_entries'],
        },
        slots: [],
      })

      const powersync = await PgWireClient.connect({
        host: '127.0.0.1',
        port,
        user: 'supacloud_powersync',
        database: 'postgres',
        password,
      })
      try {
        expect((await powersync.query<{ count: number }>('select count(*)::integer as count from public.lab_entries')).rows)
          .toEqual([{ count: 0 }])
        await expect(powersync.query('create table public.forbidden (id integer)')).rejects.toMatchObject({ code: '42501' })
      } finally {
        await powersync.close()
      }

      await backend.db.exec(`
        create table public.not_published (id integer primary key);
        grant select on public.not_published to supacloud_powersync;
      `)
      const drifted = await inspectPowerSyncReadiness(backend.db.engine, replication)
      expect(drifted.ready).toBe(false)
      expect(drifted.blockers).toContain('POWERSYNC_ROLE_SELECT_OUTSIDE_ALLOWLIST')
      expect(drifted.role.unexpected_selectable_tables).toEqual(['public.not_published'])
    } finally {
      await backend.close()
    }
  }, 180_000)

  test('returns an existing native data directory to the lightweight defaults after profile shutdown', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'supacloud-lite-native-profile-reset-'))
    temporaryDirectories.push(projectRoot)
    const dataDir = join(projectRoot, 'pgdata')
    const replication = {
      profile: 'powersync' as const,
      host: '127.0.0.1',
      port: await freePort(),
      allowCidrs: ['127.0.0.1/32'],
      publicationTables: ['public.placeholder'],
      password: `powersync-${crypto.randomUUID()}-${crypto.randomUUID()}`,
    }
    const profiled = await createNativeEngine({ dataDir, replication })
    expect((await replicationSettings(profiled)).rows).toEqual([{
      listen_addresses: '127.0.0.1',
      wal_level: 'logical',
      max_wal_senders: '4',
      max_replication_slots: '4',
    }])
    await profiled.close()

    const lightweight = await createNativeEngine({ dataDir })
    try {
      expect((await replicationSettings(lightweight)).rows).toEqual([{
        listen_addresses: '',
        wal_level: 'minimal',
        max_wal_senders: '0',
        max_replication_slots: '0',
      }])
    } finally {
      await lightweight.close()
    }
  }, 180_000)
})

function wireClient(): PgWireClient {
  return {
    onNotification: null,
    query: async () => ({ rows: [] }),
    exec: async () => [],
    close: async () => undefined,
  } as unknown as PgWireClient
}

async function freePort(): Promise<number> {
  const server = Bun.listen({ hostname: '127.0.0.1', port: 0, socket: { data() {} } })
  const port = server.port
  server.stop(true)
  return port
}

function replicationSettings(engine: Awaited<ReturnType<typeof createNativeEngine>>) {
  return engine.query<{
    listen_addresses: string
    wal_level: string
    max_wal_senders: string
    max_replication_slots: string
  }>(`
    SELECT
      current_setting('listen_addresses') AS listen_addresses,
      current_setting('wal_level') AS wal_level,
      current_setting('max_wal_senders') AS max_wal_senders,
      current_setting('max_replication_slots') AS max_replication_slots
  `)
}
