import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { splitSqlStatements } from "../src/db/sql-statements";

const root = resolve(import.meta.dir, "..");
const packageRoot = dirname(fileURLToPath(import.meta.resolve("@pgflow/core/package.json")));
const metadata: unknown = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
if (typeof metadata !== "object" || metadata === null || !("version" in metadata) || metadata.version !== "0.16.0") {
    throw new Error("The reviewed pgflow bundle requires @pgflow/core 0.16.0");
}
const directory = resolve(packageRoot, "dist/supabase/migrations");
const files = readdirSync(directory).filter((name) => name.endsWith(".sql")).sort();
if (files.length !== 23) throw new Error("Unexpected pgflow migration inventory");

// Only the hosted-platform supervision is replaced. Workflow SQL stays upstream.
const hostedFunctions = "(?:ensure_workers|cleanup_ensure_workers_logs|setup_ensure_workers_cron|setup_requeue_stalled_tasks_cron)";
const hostedDefinition = new RegExp(`^(?:CREATE(?: OR REPLACE)? FUNCTION|COMMENT ON FUNCTION) "pgflow"\\."${hostedFunctions}"`);
let removed = 0;
const migrations = files.map((name) => {
    const source = readFileSync(resolve(directory, name), "utf8");
    const statements = splitSqlStatements(source).filter((statement) => {
        const sql = statement.replace(/^(?:\s*--[^\n]*(?:\n|$))+/, "").trim();
        const omit = hostedDefinition.test(sql)
            || /^CREATE EXTENSION IF NOT EXISTS "(?:pg_cron|pg_net)"/.test(sql)
            || /^SELECT pgflow\.setup_(?:ensure_workers|requeue_stalled_tasks)_cron\(/.test(sql);
        if (omit) removed++;
        return !omit;
    });
    // Standalone tenants can persist events even without Supabase Realtime.
    const sql = statements.length === 0 ? "" : statements.join(";\n").replaceAll("realtime.send(", "pgflow._supacloud_emit(") + ";\n";
    if (sql.includes(".supabase.co") || sql.includes("vault.decrypted_secrets") || sql.includes("cron.schedule(")) {
        throw new Error(`Unadapted cloud dependency in ${name}`);
    }
    return { name, upstream_sha256: createHash("sha256").update(source).digest("hex"), sql };
});
if (removed !== 15) throw new Error(`Expected 15 hosted-only statements, received ${removed}`);
const digest = createHash("sha256").update(JSON.stringify(migrations)).digest("hex");
const result = `// Generated by scripts/bundle-pgflow.ts from Apache-2.0 @pgflow/core 0.16.0.\n`
    + `// Do not edit. See pgflow-LICENSE.txt for the upstream license.\n`
    + `export const PGFLOW_VERSION = "0.16.0";\n`
    + `export const PGFLOW_BUNDLE_SHA256 = ${JSON.stringify(digest)};\n`
    + `export const PGFLOW_MIGRATIONS = ${JSON.stringify(migrations, null, 2)} as const;\n`;
const target = resolve(root, "src/db/pgflow-bundle.ts");
if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== result) throw new Error("pgflow bundle is stale");
} else {
    writeFileSync(target, result);
    writeFileSync(resolve(root, "src/db/pgflow-LICENSE.txt"), readFileSync(resolve(packageRoot, "LICENSE")));
}
