import { readFileSync, writeFileSync } from "node:fs";
import { renderRoles, renderQueueGrants } from "../../worker/scripts/roles";
import { roleNames } from "../../worker/scripts/scheduler";

export function renderPgflowRoleBundle(): string {
  const projectRef = "supacloud-template";
  const { owner, worker, recovery } = roleNames(projectRef);
  const template = (sql: string) => sql
    .replaceAll(owner, "__SCW_OWNER__")
    .replaceAll(worker, "__SCW_WORKER__")
    .replaceAll(recovery, "__SCW_RECOVERY__")
    .replaceAll(projectRef, "__SCW_PROJECT__");
  return "// Generated by scripts/bundle-pgflow-roles.ts from packages/worker; do not edit.\n"
    + `export const PGFLOW_ROLE_SQL = ${JSON.stringify({
      roles: template(renderRoles(projectRef)),
      queues: template(renderQueueGrants(projectRef)),
    }, null, 2)} as const;\n`;
}

if (import.meta.main) {
  const target = new URL("../src/db/pgflow-role-bundle.ts", import.meta.url);
  const source = renderPgflowRoleBundle();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== source) throw new Error("PGFLOW_ROLE_BUNDLE_STALE");
  } else {
    writeFileSync(target, source);
  }
}
