import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';

/**
 * SupaCloud Assets Packer
 * 将 infra/ 目录下的所有文件转换为 Base64 编码的 TypeScript 字典，
 * 以便通过 bun build --compile 打包进单个二进制文件中。
 */

const INFRA_DIR = join(import.meta.dir, '../../../infra');
const SCRIPTS_DIR = join(import.meta.dir, '../../../scripts');
const OUTPUT_FILE = join(import.meta.dir, '../src/assets.gen.ts');

async function getFiles(dir: string): Promise<string[]> {
    const dirents = await readdir(dir, { withFileTypes: true });
    const files = await Promise.all(dirents.map((dirent) => {
        const res = join(dir, dirent.name);
        return dirent.isDirectory() ? getFiles(res) : res;
    }));
    return files.flat();
}

const MIME_TYPES: Record<string, string> = {
    '.sh': 'application/x-sh',
    '.sql': 'application/sql',
    '.yml': 'application/x-yaml',
    '.yaml': 'application/x-yaml',
    '.conf': 'text/plain',
    '.env': 'text/plain',
    '.example': 'text/plain',
    '.md': 'text/markdown',
    '.json': 'application/json',
    '.service': 'text/plain',
    '.template': 'text/plain',
};

async function pack() {
    console.log('🚀 Starting Assets Packing...');

    const allFiles: { path: string; source: string }[] = [
        ...(await getFiles(INFRA_DIR)).map(f => ({ path: f, source: 'infra' })),
        ...(await getFiles(SCRIPTS_DIR)).map(f => ({ path: f, source: 'scripts' })),
    ];

    let assetEntries = '';
    let count = 0;

    for (const file of allFiles) {
        const relativePath = relative(file.source === 'infra' ? INFRA_DIR : SCRIPTS_DIR, file.path);
        const key = `/${file.source}/${relativePath.replace(/\\/g, '/')}`;
        const content = await readFile(file.path);
        const extension = file.path.substring(file.path.lastIndexOf('.'));
        const mimeType = MIME_TYPES[extension] || 'application/octet-stream';

        // 使用 Base64 编码以处理可能的二进制或特殊换行符文件
        const base64 = content.toString('base64');

        assetEntries += `  '${key}': {
    content: '${base64}',
    encoding: 'base64',
    mimeType: '${mimeType}'
  },\n`;

        count++;
    }

    const output = `/**
 * AUTO GENERATED FILE - DO NOT EDIT
 * Generated by scripts/pack-assets.ts
 */

export const EMBEDDED_ASSETS: Record<string, { content: string; encoding: 'base64'; mimeType: string }> = {
${assetEntries}};

export const ASSETS_COUNT = ${count};
`;

    await mkdir(dirname(OUTPUT_FILE), { recursive: true });
    await writeFile(OUTPUT_FILE, output);

    console.log(`✅ Packed ${count} assets into ${OUTPUT_FILE}`);
}

pack().catch(console.error);
