create table if not exists public.authors (
  id integer generated by default as identity primary key,
  name text not null,
  email text unique
);

create table if not exists public.posts (
  id integer generated by default as identity primary key,
  title text not null,
  author_id integer references public.authors(id),
  published boolean not null default false,
  views integer not null default 0 check (views >= 0),
  tags text[] not null default '{}'
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid(),
  content text not null
);

alter table public.notes enable row level security;
drop policy if exists parity_note_owner on public.notes;
create policy parity_note_owner on public.notes for all to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

grant usage on schema public to anon, authenticated, service_role;
grant select on public.authors, public.posts to anon, authenticated;
grant all on public.authors, public.posts, public.notes to service_role;
grant select, insert, update, delete on public.notes to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

insert into public.authors (id, name, email) values
  (1, 'Ada', 'ada@parity.invalid'),
  (2, 'Linus', 'linus@parity.invalid')
on conflict (id) do nothing;

insert into public.posts (id, title, author_id, published, views, tags) values
  (1, 'First', 1, true, 100, '{a,b}'),
  (2, 'Second', 2, false, 50, '{b,c}')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.authors', 'id'), (select max(id) from public.authors), true);
select setval(pg_get_serial_sequence('public.posts', 'id'), (select max(id) from public.posts), true);

create or replace function public.parity_add_two(left_value integer, right_value integer)
returns integer language sql immutable as $$ select left_value + right_value $$;

create or replace function public.parity_schema_version()
returns text language sql immutable as $$ select 'supacloud-lite-parity-v1'::text $$;

grant execute on function public.parity_add_two(integer, integer) to anon, authenticated, service_role;
grant execute on function public.parity_schema_version() to anon, authenticated, service_role;
