const RUNTIME_OWNED_SECRET_NAMES = new Set([
  "JWT_SECRET",
  "JWT_KEYS",
  "JWT_JWKS",
  "SUPACLOUD_THIRD_PARTY_JWT_POLICY",
  "SUPACLOUD_AUTH_RUNTIME_MODE",
  "SUPACLOUD_AUTH_AUTHORITY_REF",
  "SUPACLOUD_AUTH_ISSUER",
  "SUPACLOUD_INTERNAL_SUPABASE_URL",
  "SUPACLOUD_INTERNAL_AUTH_URL",
  "SUPACLOUD_INTERNAL_REST_URL",
  "SUPACLOUD_INTERNAL_POSTGREST_PORT",
  "SUPACLOUD_INTERNAL_GOTRUE_PORT",
  "SUPACLOUD_PROJECT_REF",
  "SUPACLOUD_PROJECT_API_HOST",
  "SUPACLOUD_BACKGROUND_INTERNAL_TOKEN",
  "X_PROJECT_REF",
]);

export function isRuntimeOwnedSecretName(name: string): boolean {
  const normalized = name.trim().toUpperCase();
  return normalized.startsWith("SUPABASE_")
    || RUNTIME_OWNED_SECRET_NAMES.has(normalized);
}
